import baseWorker from './index.js';
import { discoverAll } from './discovery-v2.js';
import { diagnoseKnownLocalSources } from './discovery-anchors.js';
import { HOME_ZIP, eligibleZips, enrichLocation } from './zip-geo.js';
const RELEASE='3.22.0';
const RELEASE_BUILD='v3.22.0-geographic-coverage-and-address-validation';
const RELEASE_FINGERPRINT='f4d76955fd6028fef1c2ed6eac963546a0bfbb6b';
function params(request){const u=new URL(request.url),q=u.searchParams;const interests=String(q.get('interests')||'').split(',').map(x=>x.trim()).filter(Boolean);const city=q.get('city')||'Mesopotamia';const state=q.get('state')||'OH';const legacy=Number(q.get('radius')||30);const groupRadius=Number(q.get('groupRadius')||legacy);const eventRadius=Number(q.get('eventRadius')||legacy);const jobRadius=Number(q.get('jobRadius')||15);const partTime=q.get('partTime')!=='false';return{interests,city,state,groupRadius,eventRadius,jobRadius,partTime,searchParams:q};}
function json(data){return new Response(JSON.stringify(data,null,2),{status:200,headers:{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Cache-Control':'no-store'}});}
function strictResults(items,radius){return(items||[]).map(x=>enrichLocation(x,radius)).filter(Boolean);}
function release(data,p){const groups=strictResults(data.groups,p.groupRadius),events=strictResults(data.events,p.eventRadius),jobs=strictResults(data.jobs,p.jobRadius);return{...data,groups,events,jobs,deployment:{version:RELEASE,build:RELEASE_BUILD,sourceCommit:RELEASE_FINGERPRINT,entrypoint:'worker/coverage.js'},coverage:{...(data.coverage||{}),homeZip:HOME_ZIP,groupRadius:p.groupRadius,eventRadius:p.eventRadius,jobRadius:p.jobRadius,groupEligibleZipCount:eligibleZips(p.groupRadius).length,eventEligibleZipCount:eligibleZips(p.eventRadius).length,jobEligibleZipCount:eligibleZips(p.jobRadius).length,hardZipGate:true,prefetchFiltering:true,searchEvidence:true,independentRadii:true,configurableExclusions:true,diagnosticLocalAnchors:true,strictOutputAddressGate:true,deploymentIdentity:'source-commit-pinned'}};}
async function run(request){const p=params(request),result=await discoverAll(p),anchorDiagnostics=diagnoseKnownLocalSources(result);const out=release({ok:true,version:RELEASE,build:RELEASE_BUILD,architecture:'organization-first / broader organic-first / diagnostic regression fixtures / candidate-prefetch ZIP gate / strict page-validation physical-address gate / independent ZIP radii / configurable exclusions / ranked search evidence',...result,diagnostics:[...(result.diagnostics||[]),...anchorDiagnostics]},p);out.discoveryHealth={...(out.discoveryHealth||{}),organicGroups:out.groups.length,organicEvents:out.events.length,jobs:out.jobs.length,strictOutputAddressGate:true};return out;}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/test')return json(await run(request));if(url.pathname==='/groups'||url.pathname==='/events'||url.pathname==='/jobs'||url.pathname==='/discover'){const result=await run(request);if(url.pathname==='/groups')return json({...result,items:result.groups,events:undefined,jobs:undefined});if(url.pathname==='/events')return json({...result,items:result.events,groups:undefined,jobs:undefined});if(url.pathname==='/jobs')return json({...result,items:result.jobs,groups:undefined,events:undefined});return json(result);}return baseWorker.fetch(request,env);}};