import { parseJobs } from './index.js';
import { HOME_ZIP, eligibleZips, passesHardZipGate, bestLocation } from './zip-geo.js';
import { parseExclusions, isExcluded, exclusionQuery, exclusionText } from './exclusions.js';

const GROUP_TYPES = ['association','society','club','guild','chapter','organization','foundation','conservancy','preservation','museum','library','historical','heritage','nature','conservation','volunteer','community'];
const GROUP_LENS = ['community organizations','historical societies','museums','nature conservation','traditional crafts','archaeology','volunteer groups','gardening clubs'];
const JOB_LENS = ['maintenance','welding fabrication','mechanic technician','parks recreation','museum archaeology','warehouse material handling','grounds laborer','facility technician'];
const EVENT_RE = /event|calendar|meeting|workshop|program|programme|exhibit|exhibition|festival|fair|lecture|tour|open house|class|demo|registration|tickets|rsvp/i;
const ORG_RE = /association|society|club|guild|chapter|organization|organisation|foundation|conservancy|preservation|museum|library|historical|heritage|nature|conservation|volunteer|community/i;
const JOB_RE = /job|jobs|career|careers|employment|hiring|position|apply|application|opening|vacancy|vacancies|technician|welder|welding|fabricat|mechanic|warehouse|laborer|parks|grounds|recreation|museum|archaeology|custod|maintenance|delivery|transportation|library|facility/i;
const NOISE_RE = /ancient mesopotamia|mesopotamian|mesopotamia river|louisiana|church point/i;
const OUTSIDE_STATE_RE = /\b(?:alabama|alaska|arizona|arkansas|california|colorado|connecticut|delaware|florida|georgia|idaho|illinois|indiana|iowa|kansas|kentucky|louisiana|maine|maryland|massachusetts|michigan|minnesota|mississippi|missouri|montana|nebraska|nevada|new jersey|new mexico|new york|north carolina|north dakota|oklahoma|oregon|pennsylvania|rhode island|south carolina|south dakota|tennessee|texas|utah|vermont|virginia|washington|west virginia|wisconsin|wyoming)\b/i;
const OH_RE = /\b(?:ohio|oh)\b/i;
const JUNK_HOST_RE = /(?:facebook|instagram|linkedin|youtube|tiktok|pinterest|x\.com|twitter|wikipedia|yelp|tripadvisor|google|googleusercontent|googleapis|accounts|drive)\./i;
const CONTENT_HOST_RE = /(?:indeed|glassdoor|ziprecruiter|simplyhired|monster|britannica|merriam-webster|newsbreak|restaurantji|weather)\./i;

function clean(s) { return String(s || '').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'\"').replace(/&#39;|&#x27;/gi,"'").replace(/\s+/g,' ').trim(); }
function host(url) { try { return new URL(url).hostname.toLowerCase(); } catch { return ''; } }
function key(url) { try { const u = new URL(url); return `${u.hostname.toLowerCase()}${u.pathname.replace(/\/$/,'')}`; } catch { return String(url || '').toLowerCase(); } }
function validUrl(url) { try { const u = new URL(url); return /^https?:$/.test(u.protocol) && !JUNK_HOST_RE.test(u.hostname); } catch { return false; } }
function decodeSearchUrl(href) { try { const u = new URL(href); if (!/(^|\.)bing\.com$/i.test(u.hostname) || !/^\/ck\/a/i.test(u.pathname)) return href; let raw = u.searchParams.get('u') || ''; if (!raw) return href; if (raw.startsWith('a1')) raw = raw.slice(2); raw = raw.replace(/-/g,'+').replace(/_/g,'/'); while (raw.length % 4) raw += '='; const decoded = atob(raw); return /^https?:\/\//i.test(decoded) ? decoded : href; } catch { return href; } }
function extractSearchResults(html) { const out=[],seen=new Set(); const blocks=[...html.matchAll(/<li[^>]+class=["'][^"']*b_algo[^"']*["'][^>]*>([\s\S]*?)<\/li>/gi)].map(m=>m[1]); for(const block of blocks){const m=block.match(/<h2[^>]*>\s*<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i);if(!m)continue;const url=decodeSearchUrl(m[1]),title=clean(m[2]),evidence=clean(block);if(!validUrl(url)||!title||seen.has(key(url)))continue;seen.add(key(url));out.push({url,title,text:title,snippet:evidence,evidence});} return out.slice(0,12); }
async function search(query,budget){ if(budget.used>=budget.limit)return {results:[],error:'fetch budget exhausted'}; budget.used++; try{const u=new URL('https://www.bing.com/search');u.searchParams.set('q',query);u.searchParams.set('count','10');const r=await fetch(u.href,{redirect:'follow',headers:{'User-Agent':'Opportunity-Finder/3.15-discovery','Accept':'text/html,application/xhtml+xml'}});const html=await r.text();return r.ok?{results:extractSearchResults(html),status:r.status}:{results:[],status:r.status};}catch(e){return {results:[],error:String(e?.message||e)};} }
async function fetchPage(url,budget){if(budget.used>=budget.limit)return null;budget.used++;try{const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Opportunity-Finder/3.15-discovery','Accept':'text/html,application/xhtml+xml,application/json,text/xml,*/*'}});if(!r.ok)return null;const html=await r.text();return {url:r.url||url,html,title:clean((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||url),description:clean((html.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']*)/i)||[])[1]||'')};}catch{return null;}}
function gate(c,type,radius,exclusions,context=''){const evidence=`${c.url} ${c.title||''} ${c.text||''} ${c.snippet||''} ${c.evidence||''} ${context}`;if(isExcluded(evidence,exclusions,type))return {ok:false,reason:'excluded term'};if(NOISE_RE.test(evidence))return {ok:false,reason:'search noise'};if(OUTSIDE_STATE_RE.test(evidence)&&!OH_RE.test(evidence))return {ok:false,reason:'outside-state evidence'};if(!passesHardZipGate(evidence,radius))return {ok:false,reason:'hard ZIP gate failed before fetch'};return {ok:true,location:bestLocation(evidence,radius)};}
function groupQueries(interests,radius,exclusions){const zips=eligibleZips(radius).slice(0,12),cats=(interests.length?interests:GROUP_LENS).slice(0,8),suffix=exclusionQuery(exclusions,'groups');return cats.map((cat,i)=>{const z=zips[i%zips.length];return `"${z.zip}" "${z.city}" Ohio "${cat}" (${GROUP_TYPES.slice(0,8).join(' OR ')}) ${suffix}`;});}
function jobQueries(interests,radius,exclusions){const zips=eligibleZips(radius).slice(0,12),cats=(interests.length?interests:JOB_LENS).slice(0,8),suffix=exclusionQuery(exclusions,'jobs');return cats.map((cat,i)=>{const z=zips[i%zips.length];return `"${z.zip}" "${z.city}" Ohio "${cat}" (jobs OR careers OR employment OR hiring) ${suffix}`;});}
function eventQuery(org,exclusions){return `"${org.name}" "${org.zip}" "${org.city}" Ohio (events OR calendar OR workshop OR program) ${exclusionQuery(exclusions,'events')}`;}
function pageLocation(page,radius){return bestLocation(`${page.title} ${page.description} ${page.html.slice(0,50000)}`,radius);}
function makeGroup(page,candidate,radius){const loc=pageLocation(page,radius);if(!loc)return null;return {title:page.title||host(page.url),name:page.title||host(page.url),url:page.url,link:page.url,description:page.description||clean(page.html).slice(0,500),location:`${loc.city}, OH ${loc.zip}`,city:loc.city,state:'OH',zip:loc.zip,distance:loc.distance,distanceMiles:loc.distance,source:'organic-search',discoverySource:'organic-search'};}
function validGroup(page,candidate,radius,exclusions){const text=`${page.title} ${page.description} ${page.html.slice(0,50000)} ${candidate.evidence||''}`;return !isExcluded(text,exclusions,'groups')&&!NOISE_RE.test(text)&&ORG_RE.test(text)&&!!pageLocation(page,radius);}
function parseEvents(page,org,radius,exclusions){const events=[];for(const m of page.html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const data=JSON.parse(m[1].trim()),list=Array.isArray(data)?data:data?.['@graph']||[data];for(const x of list){const type=Array.isArray(x?.['@type'])?x['@type'].join(' '):String(x?.['@type']||'');if(!/Event/i.test(type))continue;const loc=typeof x.location==='string'?clean(x.location):clean([x.location?.name,x.location?.streetAddress,x.location?.addressLocality,x.location?.addressRegion,x.location?.postalCode].filter(Boolean).join(', '));const combined=`${x.name||''} ${x.description||''} ${loc}`;if(!x.name||!EVENT_RE.test(combined)||isExcluded(combined,exclusions,'events')||NOISE_RE.test(combined))continue;const best=bestLocation(combined,radius);if(!best)continue;const url=x.url?new URL(x.url,page.url).href:page.url;events.push({title:clean(x.name),name:clean(x.name),url,link:url,organization:org.name,location:`${best.city}, OH ${best.zip}`,city:best.city,state:'OH',zip:best.zip,distance:best.distance,distanceMiles:best.distance,date:x.startDate||'',endDate:x.endDate||'',description:clean(x.description||'').slice(0,1000),source:'organic-event-jsonld',discoverySource:'organic-search'});}}catch{}}return events;}

export async function discoverAll({interests=[],city='Mesopotamia',state='OH',groupRadius=30,eventRadius=30,jobRadius=15,partTime=true,searchParams=new URLSearchParams()}){
 const exclusions=parseExclusions(searchParams),budget={used:0,limit:44},diagnostics=[],groups=[],events=[],jobs=[];
 const candidates=new Map();
 for(const query of groupQueries(interests,groupRadius,exclusions)){const r=await search(query,budget);diagnostics.push({stage:'group-search',query,candidates:r.results.length,status:r.status||0,error:r.error||null});for(const c0 of r.results){const c={...c0,query},g=gate(c,'groups',groupRadius,exclusions,query);if(!g.ok){diagnostics.push({stage:'group-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,geoEvidence:`${c.title||''} ${c.snippet||''} ${query}`});continue;}candidates.set(key(c.url),c);}if(budget.used>=budget.limit)break;}
 for(const c of [...candidates.values()].slice(0,12)){const p=await fetchPage(c.url,budget);if(!p){diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'fetch failed'});continue;}if(!validGroup(p,c,groupRadius,exclusions)){diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'organization or ZIP validation failed'});continue;}const item=makeGroup(p,c,groupRadius);if(item&&!groups.some(x=>key(x.url)===key(item.url)))groups.push(item);if(groups.length>=8||budget.used>=budget.limit)break;}
 const eventOrgs=groups.slice(0,8);
 for(const org of eventOrgs){if(budget.used>=budget.limit)break;const p=await fetchPage(org.url,budget);if(!p)continue;const found=parseEvents(p,org,eventRadius,exclusions);diagnostics.push({stage:'event-page-parse',organization:org.name,candidates:found.length});events.push(...found);}
 if(events.length<8){for(const org of eventOrgs.slice(0,6)){if(budget.used>=budget.limit)break;const query=eventQuery(org,exclusions),r=await search(query,budget);diagnostics.push({stage:'event-search',organization:org.name,query,candidates:r.results.length,status:r.status||0});for(const c0 of r.results){const c={...c0,query},g=gate(c,'events',eventRadius,exclusions,query);if(!g.ok){diagnostics.push({stage:'event-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,geoEvidence:`${c.title||''} ${c.snippet||''} ${query}`});continue;}if(!EVENT_RE.test(`${c.title} ${c.snippet}`))continue;const p=await fetchPage(c.url,budget);if(!p)continue;events.push(...parseEvents(p,org,eventRadius,exclusions));if(events.length>=8)break;}}}
 const seenJobs=new Set();for(const query of jobQueries(interests,jobRadius,exclusions)){if(budget.used>=budget.limit)break;const r=await search(query,budget);diagnostics.push({stage:'job-search',query,candidates:r.results.length,status:r.status||0});for(const c0 of r.results){if(budget.used>=budget.limit)break;const c={...c0,query},g=gate(c,'jobs',jobRadius,exclusions,query);if(!g.ok){diagnostics.push({stage:'job-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,zip:g.location?.zip||null,distanceMiles:g.location?.distance??null,geoEvidence:`${c.title||''} ${c.snippet||''} ${query}`});continue;}if(CONTENT_HOST_RE.test(host(c.url))&&!JOB_RE.test(`${c.title} ${c.snippet}`))continue;const p=await fetchPage(c.url,budget);if(!p)continue;const found=parseJobs(p.html||'',p.url,interests,city,state,jobRadius,{source:'validated job page',partTime});for(const x of found){const k=`${String(x.title||'').toLowerCase()}|${String(x.url||'').toLowerCase()}`;if(seenJobs.has(k)||isExcluded(`${x.title||''} ${x.description||''} ${x.employer||''}`,exclusions,'jobs'))continue;seenJobs.add(k);jobs.push({...x,zip:x.zip||g.location.zip,city:x.city||g.location.city,state:x.state||state,distanceMiles:x.distanceMiles??g.location.distance,distance:x.distance??g.location.distance});}if(jobs.length>=12)break;}}
 const uniqueEvents=[],eventKeys=new Set();for(const e of events){const k=`${String(e.title||'').toLowerCase()}|${e.url}`;if(eventKeys.has(k)||isExcluded(`${e.title||''} ${e.description||''}`,exclusions,'events'))continue;eventKeys.add(k);uniqueEvents.push(e);}return {ok:true,version:'3.15.0',build:'v3.15.0-configurable-exclusions',groups:groups.slice(0,12),events:uniqueEvents.slice(0,12),jobs:jobs.slice(0,12),exclusions,exclusionTerms:{global:exclusionText(exclusions,'groups').filter(x=>!(exclusions.groups||[]).includes(x)),groups:exclusions.groups,events:exclusions.events,jobs:exclusions.jobs},fetchBudget:budget,diagnostics,eligible:{groups:eligibleZips(groupRadius),events:eligibleZips(eventRadius),jobs:eligibleZips(jobRadius)}};
}
