import { parseJobs } from './index.js';
import { eligibleZips, passesHardZipGate, bestLocation } from './zip-geo.js';
import { parseExclusions, isExcluded, exclusionQuery } from './exclusions.js';

const GROUP_LENS=['(association OR society OR club OR organization)','(historical OR heritage OR museum OR "living history")','(blacksmith OR blacksmithing OR forge OR "traditional crafts")','(beekeepers OR beekeeping OR apiary)','(nature OR conservation OR watershed OR parks)','(gardening OR horticulture OR garden club)','(archaeology OR archaeological OR preservation)','(volunteer OR community OR nonprofit OR foundation)'];
const EVENT_LENS='(events OR calendar OR festival OR workshop OR meeting OR program OR exhibit OR demonstration)';
const JOB_LENS=['maintenance','welding fabrication','mechanic technician','parks recreation','museum archaeology','warehouse material handling','grounds laborer','facility technician'];
const EVENT_RE=/event|calendar|meeting|workshop|program|programme|exhibit|exhibition|festival|fair|lecture|tour|open house|class|demo|registration|tickets|rsvp/i;
const ORG_RE=/association|society|club|guild|chapter|organization|organisation|foundation|conservancy|preservation|museum|library|historical|heritage|nature|conservation|volunteer|community|beekeep|blacksmith|forge|apiary/i;
const JOB_RE=/job|jobs|career|careers|employment|hiring|position|apply|opening|vacanc|technician|welder|welding|fabricat|mechanic|warehouse|laborer|parks|grounds|recreation|museum|archaeology|custod|maintenance|delivery|transportation|library|facility/i;
const NOISE_RE=/ancient mesopotamia|mesopotamian|mesopotamia river|church point/i;
const OUTSIDE_STATE_RE=/\b(?:alabama|alaska|arizona|arkansas|california|colorado|connecticut|delaware|florida|georgia|idaho|illinois|indiana|iowa|kansas|kentucky|louisiana|maine|maryland|massachusetts|michigan|minnesota|mississippi|missouri|montana|nebraska|nevada|new jersey|new mexico|new york|north carolina|north dakota|oklahoma|oregon|pennsylvania|rhode island|south carolina|south dakota|tennessee|texas|utah|vermont|virginia|washington|west virginia|wisconsin|wyoming)\b/i;
const OH_RE=/\b(?:ohio|oh)\b/i;
const JUNK_HOST_RE=/(?:facebook|instagram|linkedin|youtube|tiktok|pinterest|x\.com|twitter|wikipedia|yelp|tripadvisor|google|googleusercontent|googleapis|accounts|drive)\./i;
const JOB_AGG_RE=/(?:indeed|glassdoor|ziprecruiter|simplyhired|monster)\./i;
function clean(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'\"').replace(/&#39;|&#x27;/gi,"'").replace(/\s+/g,' ').trim();}
function dec(s){return String(s||'').replace(/&amp;/gi,'&').replace(/&quot;/gi,'\"').replace(/&#39;|&#x27;/gi,"'").replace(/&#x2F;|&#47;/gi,'/').replace(/&#61;/gi,'=').replace(/&#x3D;/gi,'=').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');}
function host(u){try{return new URL(u).hostname.toLowerCase();}catch{return '';}}
function key(u){try{const x=new URL(u);return x.hostname.toLowerCase()+x.pathname.replace(/\/$/,'');}catch{return String(u||'').toLowerCase();}}
function valid(u){try{const x=new URL(u);return /^https?:$/.test(x.protocol)&&!JUNK_HOST_RE.test(x.hostname)&&!/(?:\.xxx|pornhub|xnxx|xvideos)\b/i.test(x.hostname);}catch{return false;}}
function bingUrl(h){try{const s=dec(h),u=new URL(s);if(!/(^|\.)bing\.com$/i.test(u.hostname)||!/^\/ck\/a/i.test(u.pathname))return s;for(const n of ['u','url','r']){const raw=u.searchParams.get(n)||'';if(!raw)continue;try{let v=decodeURIComponent(raw);if(/^https?:\/\//i.test(v))return v;v=v.replace(/^a1/,'').replace(/-/g,'+').replace(/_/g,'/');while(v.length%4)v+='=';v=atob(v);if(/^https?:\/\//i.test(v))return v;}catch{}}return s;}catch{return dec(h);}}
function results(html){const out=[],seen=new Set(),s=dec(html);for(const b of [...s.matchAll(/<li[^>]+class=[\"'][^\"']*b_algo[^\"']*[\"'][^>]*>([\s\S]*?)<\/li>/gi)].map(x=>x[1])){const m=b.match(/<h2[^>]*>\s*<a[^>]+href=[\"']([^\"']+)[\"'][^>]*>([\s\S]*?)<\/a>/i);if(!m)continue;const url=bingUrl(m[1]),title=clean(m[2]),snippet=clean(b);if(!valid(url)||!title||seen.has(key(url)))continue;seen.add(key(url));out.push({url,title,text:title,snippet,evidence:snippet});}return out.slice(0,10);}
async function search(q,b){if(b.used>=b.limit)return {results:[],error:'fetch budget exhausted'};b.used++;try{const u=new URL('https://www.bing.com/search');u.searchParams.set('q',q);u.searchParams.set('count','10');u.searchParams.set('setlang','en-US');const r=await fetch(u,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; Opportunity-Finder/3.19)','Accept':'text/html,application/xhtml+xml'}});const h=await r.text();return {results:r.ok?results(h):[],status:r.status};}catch(e){return {results:[],error:String(e?.message||e)};}}
async function page(url,b){if(b.used>=b.limit)return null;b.used++;try{const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; Opportunity-Finder/3.19)','Accept':'text/html,application/xhtml+xml,application/json,text/xml,*/*'}});if(!r.ok)return null;const h=await r.text();return {url:r.url||url,html:h,title:clean((h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||url),description:clean((h.match(/<meta[^>]+(?:name|property)=[\"'](?:description|og:description)[\"'][^>]+content=[\"']([^\"']*)/i)||[])[1]||'')};}catch{return null;}}
function ev(c){return `${c.url} ${c.title||''} ${c.text||''} ${c.snippet||''} ${c.evidence||''}`;}
function gate(c,type,r,e){const s=ev(c);if(isExcluded(s,e,type))return {ok:false,reason:'excluded term'};if(NOISE_RE.test(s))return {ok:false,reason:'search noise'};if(OUTSIDE_STATE_RE.test(s)&&!OH_RE.test(s))return {ok:false,reason:'outside-state evidence'};if(!passesHardZipGate(s,r))return {ok:false,reason:'hard ZIP gate failed before fetch'};return {ok:true,location:bestLocation(s,r)};}
function zips(radius,n=8){const a=eligibleZips(radius),o=[],seen=new Set();if(!a.length)return o;const add=x=>{if(x&&!seen.has(x.zip)){seen.add(x.zip);o.push(x);}};add(a[0]);for(let i=1;i<n-1;i++)add(a[Math.round(i*(a.length-1)/(n-1))]);add(a[a.length-1]);return o;}
function gq(interests,r,e){const a=zips(r),cats=interests.length?interests.map(x=>`(${x})`):GROUP_LENS,s=exclusionQuery(e,'groups');return a.map((x,i)=>`\"${x.city}\" \"${x.zip}\" Ohio ${cats[i%cats.length]} ${s}`);}
function eq(r,e){const s=exclusionQuery(e,'events');return zips(r).map(x=>`\"${x.city}\" \"${x.zip}\" Ohio ${EVENT_LENS} ${s}`);}
function jq(interests,r,e){const a=zips(r),cats=interests.length?interests:JOB_LENS,s=exclusionQuery(e,'jobs');return a.map((x,i)=>`\"${x.city}\" \"${x.zip}\" Ohio \"${cats[i%cats.length]}\" (jobs OR careers OR hiring) ${s}`);}
function loc(p,r){return bestLocation(`${p.title} ${p.description} ${p.html.slice(0,60000)}`,r);}
function group(p,r){const x=loc(p,r);if(!x)return null;return {title:p.title||host(p.url),name:p.title||host(p.url),url:p.url,link:p.url,description:p.description||clean(p.html).slice(0,500),location:`${x.city}, OH ${x.zip}`,city:x.city,state:'OH',zip:x.zip,distance:x.distance,distanceMiles:x.distance,source:'organic-search',discoverySource:'organic-search'};}
function validGroup(p,c,r,e){const s=`${p.title} ${p.description} ${p.html.slice(0,60000)} ${ev(c)}`;return ORG_RE.test(s)&&!isExcluded(s,e,'groups')&&!NOISE_RE.test(s)&&!!loc(p,r);}
function parseEvents(p,o,r,e){const out=[];for(const m of p.html.matchAll(/<script[^>]+type=[\"']application\/ld\+json[\"'][^>]*>([\s\S]*?)<\/script>/gi)){try{const d=JSON.parse(m[1].trim()),a=Array.isArray(d)?d:d?.['@graph']||[d];for(const x of a){const t=Array.isArray(x?.['@type'])?x['@type'].join(' '):String(x?.['@type']||'');if(!/Event/i.test(t)||!x.name)continue;const l=typeof x.location==='string'?clean(x.location):clean([x.location?.name,x.location?.streetAddress,x.location?.addressLocality,x.location?.addressRegion,x.location?.postalCode].filter(Boolean).join(', ')),s=`${x.name} ${x.description||''} ${l}`;if(!EVENT_RE.test(s)||isExcluded(s,e,'events')||NOISE_RE.test(s))continue;const z=bestLocation(s,r);if(!z)continue;const u=x.url?new URL(x.url,p.url).href:p.url;out.push({title:clean(x.name),name:clean(x.name),url:u,link:u,organization:o.name,location:`${z.city}, OH ${z.zip}`,city:z.city,state:'OH',zip:z.zip,distance:z.distance,distanceMiles:z.distance,date:x.startDate||'',endDate:x.endDate||'',description:clean(x.description||'').slice(0,1000),source:'organic-event-jsonld',discoverySource:'organic-search'});}}catch{}}return out;}
function fallbackEvent(p,r){const z=loc(p,r),t=p.title||host(p.url),s=`${t} ${p.description} ${clean(p.html).slice(0,12000)}`;if(!z||!EVENT_RE.test(s))return null;return {title:t,name:t,url:p.url,link:p.url,organization:'Organic local discovery',location:`${z.city}, OH ${z.zip}`,city:z.city,state:'OH',zip:z.zip,distance:z.distance,distanceMiles:z.distance,description:p.description||clean(p.html).slice(0,700),source:'organic-event-page',discoverySource:'organic-search'};}
function score(c,re){const s=`${c.title} ${c.snippet}`;let n=re.test(s)?4:0;if(ORG_RE.test(s))n+=2;if(/\b(?:ohio|oh)\b/i.test(s))n+=2;if(/\b\d{5}\b/.test(s))n+=2;return n;}

export async function discoverAll({interests=[],city='Mesopotamia',state='OH',groupRadius=30,eventRadius=30,jobRadius=15,partTime=true,searchParams=new URLSearchParams()}){
 const exclusions=parseExclusions(searchParams),budget={used:0,limit:44},diagnostics=[],groups=[],events=[],jobs=[];
 const candidates=new Map();
 for(const q of gq(interests,groupRadius,exclusions)){const r=await search(q,budget);diagnostics.push({stage:'group-search',query:q,candidates:r.results.length,status:r.status||0,error:r.error||null});for(const c of r.results){const g=gate(c,'groups',groupRadius,exclusions);if(g.ok)candidates.set(key(c.url),c);else diagnostics.push({stage:'group-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,geoEvidence:ev(c)});}}
 const pages=[];for(const c of [...candidates.values()].sort((a,b)=>score(b,ORG_RE)-score(a,ORG_RE)).slice(0,8)){if(budget.used>=budget.limit)break;const p=await page(c.url,budget);if(!p){diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'fetch failed'});continue;}if(!validGroup(p,c,groupRadius,exclusions)){diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'organization or ZIP validation failed'});continue;}const x=group(p,groupRadius);if(x&&!groups.some(y=>key(y.url)===key(x.url))){groups.push(x);pages.push({org:x,page:p});}}
 for(const x of pages){const f=parseEvents(x.page,x.org,eventRadius,exclusions);diagnostics.push({stage:'event-page-parse',organization:x.org.name,candidates:f.length});events.push(...f);}
 const ec=new Map();if(events.length<12)for(const q of eq(eventRadius,exclusions)){if(budget.used>=budget.limit)break;const r=await search(q,budget);diagnostics.push({stage:'event-search',query:q,candidates:r.results.length,status:r.status||0,error:r.error||null});for(const c of r.results){const g=gate(c,'events',eventRadius,exclusions);if(g.ok&&EVENT_RE.test(`${c.title} ${c.snippet}`))ec.set(key(c.url),c);else if(!g.ok)diagnostics.push({stage:'event-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,geoEvidence:ev(c)});}}
 for(const c of [...ec.values()].sort((a,b)=>score(b,EVENT_RE)-score(a,EVENT_RE)).slice(0,6)){if(budget.used>=budget.limit)break;const p=await page(c.url,budget);if(!p)continue;const f=parseEvents(p,{name:p.title||host(p.url)},eventRadius,exclusions);events.push(...f);if(!f.length){const x=fallbackEvent(p,eventRadius);if(x)events.push(x);}}
 const seen=new Set();for(const q of jq(interests,jobRadius,exclusions)){if(budget.used>=budget.limit)break;const r=await search(q,budget);diagnostics.push({stage:'job-search',query:q,candidates:r.results.length,status:r.status||0,error:r.error||null});for(const c of r.results.sort((a,b)=>score(b,JOB_RE)-score(a,JOB_RE))){if(budget.used>=budget.limit)break;const g=gate(c,'jobs',jobRadius,exclusions);if(!g.ok){diagnostics.push({stage:'job-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,zip:null,distanceMiles:null,geoEvidence:ev(c)});continue;}if(JOB_AGG_RE.test(host(c.url)))continue;const p=await page(c.url,budget);if(!p)continue;for(const x of parseJobs(p.html||'',p.url,interests,city,state,jobRadius,{source:'validated job page',partTime})){const k=`${String(x.title||'').toLowerCase()}|${String(x.url||'').toLowerCase()}`;if(seen.has(k)||isExcluded(`${x.title||''} ${x.description||''} ${x.employer||''}`,exclusions,'jobs'))continue;seen.add(k);jobs.push({...x,zip:x.zip||g.location?.zip||'',city:x.city||g.location?.city||'',state:x.state||state,distanceMiles:x.distanceMiles??g.location?.distance??null,distance:x.distance??g.location?.distance??null});}if(jobs.length>=12)break;}}
 const uniq=(a,t)=>{const o=[],s=new Set();for(const x of a){const k=`${String(x.title||'').toLowerCase()}|${x.url||''}`;if(s.has(k)||isExcluded(`${x.title||''} ${x.description||''} ${x.name||''}`,exclusions,t))continue;s.add(k);o.push(x);}return o;};
 return {groups:uniq(groups,'groups').slice(0,12),events:uniq(events,'events').slice(0,12),jobs:uniq(jobs,'jobs').slice(0,12),diagnostics,budget,discoveryHealth:{organicGroups:groups.length,organicEvents:events.length,jobs:jobs.length,fallbackActivated:false,hardZipGate:true,prefetchFiltering:true,searchEvidence:true,independentRadii:true,configurableExclusions:true}};
}
