import { parseJobs } from './index.js';
import { eligibleZips, passesHardZipGate, bestLocation } from './zip-geo.js';
import { parseExclusions, isExcluded, exclusionQuery } from './exclusions.js';

const GROUP_LENS=[
  '(association OR society OR club OR organization OR guild OR chapter)',
  '(blacksmith OR blacksmithing OR forge OR metalworking OR "traditional crafts")',
  '(historical OR heritage OR museum OR "living history" OR preservation)',
  '(beekeepers OR beekeeping OR apiary OR pollinator)',
  '(nature OR conservation OR watershed OR parks OR trails)',
  '(gardening OR horticulture OR "garden club" OR agriculture)',
  '(archaeology OR archaeological OR preservation OR historical)',
  '(volunteer OR community OR nonprofit OR foundation)'
];
const EVENT_LENS='(events OR calendar OR festival OR workshop OR meeting OR program OR exhibit OR demonstration OR class OR tour)';
const JOB_LENS=['maintenance','welding fabrication','mechanic technician','parks recreation','museum archaeology','warehouse material handling','grounds laborer','facility technician'];
const EVENT_RE=/event|calendar|meeting|workshop|program|programme|exhibit|exhibition|festival|fair|lecture|tour|open house|class|demo|registration|tickets|rsvp/i;
const ORG_RE=/association|society|club|guild|chapter|organization|organisation|foundation|conservancy|preservation|museum|library|historical|heritage|nature|conservation|volunteer|community|beekeep|blacksmith|forge|apiary|arts?|crafts?/i;
const JOB_RE=/job|jobs|career|careers|employment|hiring|position|apply|opening|vacanc|technician|welder|welding|fabricat|mechanic|warehouse|laborer|parks|grounds|recreation|museum|archaeology|custod|maintenance|delivery|transportation|library|facility/i;
const NOISE_RE=/ancient mesopotamia|mesopotamian|mesopotamia river|church point/i;
const OUTSIDE_STATE_RE=/\b(?:alabama|alaska|arizona|arkansas|california|colorado|connecticut|delaware|florida|georgia|idaho|illinois|indiana|iowa|kansas|kentucky|louisiana|maine|maryland|massachusetts|michigan|minnesota|mississippi|missouri|montana|nebraska|nevada|new jersey|new mexico|new york|north carolina|north dakota|oklahoma|oregon|pennsylvania|rhode island|south carolina|south dakota|tennessee|texas|utah|vermont|virginia|washington|west virginia|wisconsin|wyoming)\b/i;
const OH_RE=/\b(?:ohio|oh)\b/i;
const JUNK_HOST_RE=/(?:facebook|instagram|linkedin|youtube|tiktok|pinterest|x\.com|twitter|wikipedia|yelp|tripadvisor|google|googleusercontent|googleapis|accounts|drive)\./i;
const JOB_AGG_RE=/(?:indeed|glassdoor|ziprecruiter|simplyhired|monster)\./i;
function clean(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'\"').replace(/&#39;|&#x27;/gi,"'").replace(/\s+/g,' ').trim();}
function htmlDecode(s){return String(s||'').replace(/&amp;/gi,'&').replace(/&quot;/gi,'\"').replace(/&#39;|&#x27;/gi,"'").replace(/&#x2F;|&#47;/gi,'/').replace(/&#61;/gi,'=').replace(/&#x3D;/gi,'=').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');}
function host(url){try{return new URL(url).hostname.toLowerCase();}catch{return '';}}
function key(url){try{const u=new URL(url);return `${u.hostname.toLowerCase()}${u.pathname.replace(/\/$/,'')}`;}catch{return String(url||'').toLowerCase();}}
function validUrl(url){try{const u=new URL(url);return /^https?:$/.test(u.protocol)&&!JUNK_HOST_RE.test(u.hostname)&&!/(?:\.xxx|pornhub|xnxx|xvideos)\b/i.test(u.hostname);}catch{return false;}}
function decodeBing(href){try{const source=htmlDecode(href),u=new URL(source);if(!/(^|\.)bing\.com$/i.test(u.hostname)||!/^\/ck\/a/i.test(u.pathname))return source;for(const n of ['u','url','r']){const raw=u.searchParams.get(n)||'';if(!raw)continue;try{let s=decodeURIComponent(raw);if(/^https?:\/\//i.test(s))return s;s=s.replace(/^a1/,'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const d=atob(s);if(/^https?:\/\//i.test(d))return d;}catch{}}return source;}catch{return htmlDecode(href);}}
function extractResults(html){const out=[],seen=new Set(),source=htmlDecode(html);for(const block of [...source.matchAll(/<li[^>]+class=[\"'][^\"']*b_algo[^\"']*[\"'][^>]*>([\s\S]*?)<\/li>/gi)].map(m=>m[1])){const m=block.match(/<h2[^>]*>\s*<a[^>]+href=[\"']([^\"']+)[\"'][^>]*>([\s\S]*?)<\/a>/i);if(!m)continue;const url=decodeBing(m[1]),title=clean(m[2]),snippet=clean(block);if(!validUrl(url)||!title||seen.has(key(url)))continue;seen.add(key(url));out.push({url,title,text:title,snippet,evidence:snippet});}return out.slice(0,10);}
async function search(query,budget){if(budget.used>=budget.limit)return {results:[],error:'fetch budget exhausted'};budget.used++;try{const u=new URL('https://www.bing.com/search');u.searchParams.set('q',query);u.searchParams.set('count','10');u.searchParams.set('setlang','en-US');const r=await fetch(u.href,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; Opportunity-Finder/3.20)','Accept':'text/html,application/xhtml+xml'}});const html=await r.text();return {results:r.ok?extractResults(html):[],status:r.status};}catch(e){return {results:[],error:String(e?.message||e)};}}
async function fetchPage(url,budget){if(budget.used>=budget.limit)return null;budget.used++;try{const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; Opportunity-Finder/3.20)','Accept':'text/html,application/xhtml+xml,application/json,text/xml,*/*'}});if(!r.ok)return null;const html=await r.text();return {url:r.url||url,html,title:clean((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||url),description:clean((html.match(/<meta[^>]+(?:name|property)=[\"'](?:description|og:description)[\"'][^>]+content=[\"']([^\"']*)/i)||[])[1]||'')};}catch{return null;}}
function evidence(c){return `${c.url} ${c.title||''} ${c.text||''} ${c.snippet||''} ${c.evidence||''}`;}
function gate(c,type,radius,exclusions){const e=evidence(c);if(isExcluded(e,exclusions,type))return {ok:false,reason:'excluded term'};if(NOISE_RE.test(e))return {ok:false,reason:'search noise'};if(OUTSIDE_STATE_RE.test(e)&&!OH_RE.test(e))return {ok:false,reason:'outside-state evidence'};if(!passesHardZipGate(e,radius))return {ok:false,reason:'hard ZIP gate failed before fetch'};return {ok:true,location:bestLocation(e,radius)};}
function scoreGroup(c){const s=`${c.title} ${c.snippet}`;let n=0;if(ORG_RE.test(s))n+=6;if(/\b(?:ohio|oh)\b/i.test(s))n+=2;if(/\b\d{5}\b/.test(s))n+=2;if(/calendar|contact|about|membership|join|official/i.test(s))n+=1;if(/\.org\b|\.gov\b/i.test(host(c.url)))n+=2;if(JUNK_HOST_RE.test(host(c.url)))n-=10;return n;}
function scoreEvent(c){const s=`${c.title} ${c.snippet}`;let n=0;if(EVENT_RE.test(s))n+=4;if(ORG_RE.test(s))n+=2;if(/\b(?:ohio|oh)\b/i.test(s))n+=2;if(/\b\d{5}\b/.test(s))n+=2;if(/\.org\b|\.gov\b/i.test(host(c.url)))n+=2;return n;}
function scoreJob(c){const s=`${c.title} ${c.snippet}`;let n=0;if(JOB_RE.test(s))n+=5;if(/\b(?:ohio|oh)\b/i.test(s))n+=2;if(/\b\d{5}\b/.test(s))n+=2;if(JOB_AGG_RE.test(host(c.url)))n-=2;if(/\.org\b|\.gov\b/i.test(host(c.url)))n+=1;return n;}
function sampleZips(radius,count=8){return eligibleZips(radius).slice(0,count);}
function groupQueries(interests,radius,exclusions){const z=sampleZips(radius,8),cats=interests.length?interests.map(x=>`(${x})`):GROUP_LENS,suffix=exclusionQuery(exclusions,'groups'),q=[];for(const x of z){q.push(`\"${x.city}\" \"${x.zip}\" Ohio (association OR society OR club OR organization OR guild OR chapter) ${suffix}`);for(const cat of cats.slice(0,2))q.push(`\"${x.city}\" \"${x.zip}\" Ohio ${cat} ${suffix}`);}return q;}
function eventQueries(radius,exclusions){const z=sampleZips(radius,6),suffix=exclusionQuery(exclusions,'events');return z.map(x=>`\"${x.city}\" \"${x.zip}\" Ohio ${EVENT_LENS} ${suffix}`);}
function jobQueries(interests,radius,exclusions){const z=sampleZips(radius,8),cats=interests.length?interests:JOB_LENS,suffix=exclusionQuery(exclusions,'jobs');return z.map((x,i)=>`\"${x.city}\" \"${x.zip}\" Ohio \"${cats[i%cats.length]}\" (jobs OR careers OR hiring OR employment) ${suffix}`);}
function pageLocation(page,radius){return bestLocation(`${page.title} ${page.description} ${page.html.slice(0,60000)}`,radius);}
function makeGroup(page,radius,candidateLocation=null){const loc=pageLocation(page,radius)||candidateLocation;if(!loc)return null;return {title:page.title||host(page.url),name:page.title||host(page.url),url:page.url,link:page.url,description:page.description||clean(page.html).slice(0,500),location:`${loc.city}, OH ${loc.zip}`,city:loc.city,state:'OH',zip:loc.zip,distance:loc.distance,distanceMiles:loc.distance,source:'organic-search',discoverySource:'organic-search'};}
function validGroup(page,c,radius,exclusions){const t=`${page.title} ${page.description} ${page.html.slice(0,60000)} ${evidence(c)}`;return ORG_RE.test(t)&&!isExcluded(t,exclusions,'groups')&&!NOISE_RE.test(t)&&(pageLocation(page,radius)||c.location);}
function parseEvents(page,org,radius,exclusions){const events=[];for(const m of page.html.matchAll(/<script[^>]+type=[\"']application\/ld\+json[\"'][^>]*>([\s\S]*?)<\/script>/gi)){try{const data=JSON.parse(m[1].trim()),list=Array.isArray(data)?data:data?.['@graph']||[data];for(const x of list){const type=Array.isArray(x?.['@type'])?x['@type'].join(' '):String(x?.['@type']||'');if(!/Event/i.test(type)||!x.name)continue;const loc=typeof x.location==='string'?clean(x.location):clean([x.location?.name,x.location?.streetAddress,x.location?.addressLocality,x.location?.addressRegion,x.location?.postalCode].filter(Boolean).join(', '));const combined=`${x.name} ${x.description||''} ${loc}`;if(!EVENT_RE.test(combined)||isExcluded(combined,exclusions,'events')||NOISE_RE.test(combined))continue;const best=bestLocation(combined,radius);if(!best)continue;const url=x.url?new URL(x.url,page.url).href:page.url;events.push({title:clean(x.name),name:clean(x.name),url,link:url,organization:org.name,location:`${best.city}, OH ${best.zip}`,city:best.city,state:'OH',zip:best.zip,distance:best.distance,distanceMiles:best.distance,date:x.startDate||'',endDate:x.endDate||'',description:clean(x.description||'').slice(0,1000),source:'organic-event-jsonld',discoverySource:'organic-search'});}}catch{}}return events;}
function makeSearchEvent(page,radius){const loc=pageLocation(page,radius);if(!loc)return null;const title=page.title||host(page.url);const text=`${title} ${page.description} ${clean(page.html).slice(0,12000)}`;if(!EVENT_RE.test(text))return null;return {title,name:title,url:page.url,link:page.url,organization:'Organic local discovery',location:`${loc.city}, OH ${loc.zip}`,city:loc.city,state:'OH',zip:loc.zip,distance:loc.distance,distanceMiles:loc.distance,description:page.description||clean(page.html).slice(0,700),source:'organic-event-page',discoverySource:'organic-search'};}

export async function discoverAll({interests=[],city='Mesopotamia',state='OH',groupRadius=30,eventRadius=30,jobRadius=15,partTime=true,searchParams=new URLSearchParams()}){
 const exclusions=parseExclusions(searchParams),budget={used:0,limit:64},diagnostics=[],groups=[],events=[],jobs=[],groupPages=[];
 const groupCandidates=new Map();
 for(const query of groupQueries(interests,groupRadius,exclusions)){if(budget.used>=budget.limit)break;const r=await search(query,budget);diagnostics.push({stage:'group-search',query,candidates:r.results.length,status:r.status||0,error:r.error||null});for(const c of r.results){const g=gate(c,'groups',groupRadius,exclusions);if(!g.ok){diagnostics.push({stage:'group-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,geoEvidence:evidence(c)});continue;}groupCandidates.set(key(c.url),{...c,score:scoreGroup(c),location:g.location});}}
 const rankedGroups=[...groupCandidates.values()].sort((a,b)=>b.score-a.score).slice(0,10);
 for(const c of rankedGroups){if(budget.used>=budget.limit)break;const p=await fetchPage(c.url,budget);if(!p){diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'fetch failed'});continue;}if(!validGroup(p,c,groupRadius,exclusions)){diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'organization or ZIP validation failed'});continue;}const item=makeGroup(p,groupRadius,c.location);if(item&&!groups.some(x=>key(x.url)===key(item.url))){groups.push(item);groupPages.push({org:item,page:p});}if(groups.length>=10)break;}
 for(const {org,page} of groupPages){const found=parseEvents(page,org,eventRadius,exclusions);diagnostics.push({stage:'event-page-parse',organization:org.name,candidates:found.length});events.push(...found);}
 const eventCandidates=new Map();
 if(events.length<12){for(const query of eventQueries(eventRadius,exclusions)){if(budget.used>=budget.limit)break;const r=await search(query,budget);diagnostics.push({stage:'event-search',query,candidates:r.results.length,status:r.status||0,error:r.error||null});for(const c of r.results){const g=gate(c,'events',eventRadius,exclusions);if(!g.ok){diagnostics.push({stage:'event-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,geoEvidence:evidence(c)});continue;}if(!EVENT_RE.test(`${c.title} ${c.snippet}`))continue;eventCandidates.set(key(c.url),{...c,score:scoreEvent(c)});}}
  for(const c of [...eventCandidates.values()].sort((a,b)=>b.score-a.score).slice(0,6)){if(budget.used>=budget.limit)break;const p=await fetchPage(c.url,budget);if(!p)continue;const parsed=parseEvents(p,{name:p.title||host(p.url)},eventRadius,exclusions);events.push(...parsed);if(!parsed.length){const fallback=makeSearchEvent(p,eventRadius);if(fallback)events.push(fallback);}}
 }
 const seenJobs=new Set();
 for(const query of jobQueries(interests,jobRadius,exclusions)){if(budget.used>=budget.limit)break;const r=await search(query,budget);diagnostics.push({stage:'job-search',query,candidates:r.results.length,status:r.status||0,error:r.error||null});const ranked=r.results.map(c=>({...c,score:scoreJob(c)})).sort((a,b)=>b.score-a.score);for(const c of ranked){if(budget.used>=budget.limit)break;const g=gate(c,'jobs',jobRadius,exclusions);if(!g.ok){diagnostics.push({stage:'job-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,zip:null,distanceMiles:null,geoEvidence:evidence(c)});continue;}if(JOB_AGG_RE.test(host(c.url))&&c.score<5)continue;const p=await fetchPage(c.url,budget);if(!p)continue;const found=parseJobs(p.html||'',p.url,interests,city,state,jobRadius,{source:'validated job page',partTime});for(const x of found){const k=`${String(x.title||'').toLowerCase()}|${String(x.url||'').toLowerCase()}`;if(seenJobs.has(k)||isExcluded(`${x.title||''} ${x.description||''} ${x.employer||''}`,exclusions,'jobs'))continue;seenJobs.add(k);jobs.push({...x,zip:x.zip||g.location?.zip||'',city:x.city||g.location?.city||'',state:x.state||state,distanceMiles:x.distanceMiles??g.location?.distance??null,distance:x.distance??g.location?.distance??null});}if(jobs.length>=12)break;}}
 const unique=(arr,type)=>{const out=[],seen=new Set();for(const x of arr){const k=`${String(x.title||'').toLowerCase()}|${x.url||''}`;if(seen.has(k)||isExcluded(`${x.title||''} ${x.description||''} ${x.name||''}`,exclusions,type))continue;seen.add(k);out.push(x);}return out;};
 return {groups:unique(groups,'groups').slice(0,12),events:unique(events,'events').slice(0,12),jobs:unique(jobs,'jobs').slice(0,12),diagnostics,budget,discoveryHealth:{organicGroups:groups.length,organicEvents:events.length,jobs:jobs.length,fallbackActivated:false,hardZipGate:true,prefetchFiltering:true,searchEvidence:true,independentRadii:true,configurableExclusions:true,broaderQueryCoverage:true}};
}
