import { eligibleZips, passesHardZipGate, bestLocation } from './zip-geo.js';
import { parseExclusions, isExcluded, exclusionQuery } from './exclusions.js';
const GROUP_LENS=['(association OR society OR club OR organization OR guild OR chapter)','(blacksmith OR blacksmithing OR forge OR metalworking OR "traditional crafts")','(historical OR heritage OR museum OR "living history" OR preservation)','(beekeepers OR beekeeping OR apiary OR pollinator)','(nature OR conservation OR watershed OR parks OR trails)','(gardening OR horticulture OR "garden club" OR agriculture)','(archaeology OR archaeological OR preservation OR historical)','(volunteer OR community OR nonprofit OR foundation)'];
const EVENT_LENS='(events OR calendar OR festival OR workshop OR meeting OR program OR exhibit OR demonstration OR class OR tour)';
const JOB_LENS=['maintenance','welding fabrication','mechanic technician','parks recreation','museum archaeology','warehouse material handling','grounds laborer','facility technician'];
const EVENT_RE=/event|calendar|meeting|workshop|program|programme|exhibit|exhibition|festival|fair|lecture|tour|open house|class|demo|registration|tickets|rsvp/i;
const ORG_RE=/association|society|club|guild|chapter|organization|organisation|foundation|conservancy|preservation|museum|library|historical|heritage|nature|conservation|volunteer|community|beekeep|blacksmith|forge|apiary|arts?|crafts?/i;
const JOB_RE=/job|jobs|career|careers|employment|hiring|position|apply|opening|vacanc|technician|welder|welding|fabricat|mechanic|warehouse|laborer|parks|grounds|recreation|museum|archaeology|custod|maintenance|delivery|transportation|library|facility/i;
const NOISE_RE=/ancient mesopotamia|mesopotamian|mesopotamia river|church point/i;
const OUTSIDE_STATE_RE=/\b(?:alabama|alaska|arizona|arkansas|california|colorado|connecticut|delaware|florida|georgia|idaho|illinois|indiana|iowa|kansas|kentucky|louisiana|maine|maryland|massachusetts|michigan|minnesota|mississippi|missouri|montana|nebraska|nevada|new jersey|new mexico|new york|north carolina|north dakota|oklahoma|oregon|pennsylvania|rhode island|south carolina|south dakota|tennessee|texas|utah|vermont|virginia|washington|west virginia|wisconsin|wyoming)\b/i;
const OH_RE=/\b(?:ohio|oh)\b/i;
const JUNK_HOST_RE=/(?:facebook|instagram|linkedin|youtube|tiktok|pinterest|x\.com|twitter|wikipedia|yelp|tripadvisor|google|googleusercontent|googleapis|accounts|drive)\./i;
const GROUP_JUNK_HOST_RE=/(?:mapquest|mapcarta|yellowpages|superpages|manta|zoominfo|chamberofcommerce|bbb)\./i;
const GROUP_JUNK_TITLE_RE=/\b(?:map\s*&?\s*directions|mapquest|directions|locations? near|near me|directory|directories|listing|listings|reviews|reviews?\s*&?\s*ratings?|biography|about george orwell|books?|bookstore|shopping|products?|product catalog|store|shop)\b/i;
const MUNICIPAL_GROUP_RE=/\b(?:village|township|city|county)\s+(?:of\s+)?[^|:-]{0,60}\b(?:departments?|government|administration|official|offices?)\b|^welcome to the village of\b|^village departments\b/i;
const JOB_AGG_RE=/(?:indeed|glassdoor|ziprecruiter|simplyhired|monster)\./i;
const JOB_JUNK_TITLE_RE=/\b(?:biography|dictionary|definition|wikipedia|books?|bookstore|shopping|products?|store|shop|university housing|course|degree|medicine|weather|map|directions)\b/i;
function clean(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'\"').replace(/&#39;|&#x27;/gi,"'").replace(/\s+/g,' ').trim();}
function htmlDecode(s){return String(s||'').replace(/&amp;/gi,'&').replace(/&quot;/gi,'\"').replace(/&#39;|&#x27;/gi,"'").replace(/&#x2F;|&#47;/gi,'/').replace(/&#61;/gi,'=').replace(/&#x3D;/gi,'=').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');}
function host(url){try{return new URL(url).hostname.toLowerCase();}catch{return '';}}
function key(url){try{const u=new URL(url);return `${u.hostname.toLowerCase()}${u.pathname.replace(/\/$/,'')}`;}catch{return String(url||'').toLowerCase();}}
function validUrl(url){try{const u=new URL(url);return /^https?:$/.test(u.protocol)&&!JUNK_HOST_RE.test(u.hostname)&&!/(?:\.xxx|pornhub|xnxx|xvideos)\b/i.test(u.hostname);}catch{return false;}}
function decodeBing(href){try{const source=htmlDecode(href),u=new URL(source);if(!/(^|\.)bing\.com$/i.test(u.hostname)||!/^\/ck\/a/i.test(u.pathname))return source;for(const n of ['u','url','r']){const raw=u.searchParams.get(n)||'';if(!raw)continue;try{let s=decodeURIComponent(raw);if(/^https?:\/\//i.test(s))return s;s=s.replace(/^a1/,'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const d=atob(s);if(/^https?:\/\//i.test(d))return d;}catch{}}return source;}catch{return htmlDecode(href);}}
function extractResults(html){const out=[],seen=new Set(),source=htmlDecode(html);for(const block of [...source.matchAll(/<li[^>]+class=[\"'][^\"']*b_algo[^\"']*[\"'][^>]*>([\s\S]*?)<\/li>/gi)].map(m=>m[1])){const m=block.match(/<h2[^>]*>\s*<a[^>]+href=[\"']([^\"']+)[\"'][^>]*>([\s\S]*?)<\/a>/i);if(!m)continue;const url=decodeBing(m[1]),title=clean(m[2]),snippet=clean(block);if(!validUrl(url)||!title||seen.has(key(url)))continue;seen.add(key(url));out.push({url,title,text:title,snippet,evidence:snippet});}return out.slice(0,10);}
async function search(query,budget){if(budget.used>=budget.limit)return {results:[],error:'fetch budget exhausted'};budget.used++;try{const u=new URL('https://www.bing.com/search');u.searchParams.set('q',query);u.searchParams.set('count','10');u.searchParams.set('setlang','en-US');const r=await fetch(u.href,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; Opportunity-Finder/3.22)','Accept':'text/html,application/xhtml+xml'}});const html=await r.text();return {results:r.ok?extractResults(html):[],status:r.status};}catch(e){return {results:[],error:String(e?.message||e)};}}
async function fetchPage(url,budget){if(budget.used>=budget.limit)return null;budget.used++;try{const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; Opportunity-Finder/3.22)','Accept':'text/html,application/xhtml+xml,application/json,text/xml,*/*'}});if(!r.ok)return null;const html=await r.text();return {url:r.url||url,html,title:clean((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||url),description:clean((html.match(/<meta[^>]+(?:name|property)=[\"'](?:description|og:description)[\"'][^>]+content=[\"']([^\"']*)/i)||[])[1]||'')};}catch{return null;}}
function evidence(c){return `${c.url} ${c.title||''} ${c.text||''} ${c.snippet||''} ${c.evidence||''}`;}
function gate(c,type,radius,exclusions){const e=evidence(c);if(isExcluded(e,exclusions,type))return {ok:false,reason:'excluded term'};if(NOISE_RE.test(e))return {ok:false,reason:'search noise'};if(OUTSIDE_STATE_RE.test(e)&&!OH_RE.test(e))return {ok:false,reason:'outside-state evidence'};if(type==='groups'&&(GROUP_JUNK_HOST_RE.test(host(c.url))||GROUP_JUNK_TITLE_RE.test(`${c.title} ${c.snippet}`)))return {ok:false,reason:'organization search noise'};if(type==='jobs'&&(JOB_AGG_RE.test(host(c.url))||JOB_JUNK_TITLE_RE.test(c.title)))return {ok:false,reason:'job search noise'};if(!passesHardZipGate(e,radius))return {ok:false,reason:'hard ZIP gate failed before fetch'};return {ok:true,location:bestLocation(e,radius)};}
function scoreGroup(c){const s=`${c.title} ${c.snippet}`;let n=0;if(ORG_RE.test(s))n+=6;if(OH_RE.test(s))n+=2;if(/\b\d{5}\b/.test(s))n+=2;if(/calendar|contact|about|membership|join|official/i.test(s))n+=1;if(/\.org\b|\.gov\b/i.test(host(c.url)))n+=2;if(GROUP_JUNK_HOST_RE.test(host(c.url)))n-=10;if(GROUP_JUNK_TITLE_RE.test(s))n-=8;if(MUNICIPAL_GROUP_RE.test(s))n-=8;return n;}
function scoreEvent(c){const s=`${c.title} ${c.snippet}`;let n=0;if(EVENT_RE.test(s))n+=4;if(ORG_RE.test(s))n+=2;if(OH_RE.test(s))n+=2;if(/\b\d{5}\b/.test(s))n+=2;if(/\.org\b|\.gov\b/i.test(host(c.url)))n+=2;return n;}
function scoreJob(c){const s=`${c.title} ${c.snippet}`;let n=0;if(JOB_RE.test(s))n+=5;if(OH_RE.test(s))n+=2;if(/\b\d{5}\b/.test(s))n+=2;if(JOB_AGG_RE.test(host(c.url)))n-=2;if(/\.org\b|\.gov\b/i.test(host(c.url)))n+=1;return n;}
function sampleZips(radius,count=8){const all=eligibleZips(radius);if(all.length<=count)return all;const selected=[],seen=new Set();const add=x=>{if(x&&!seen.has(x.zip)){selected.push(x);seen.add(x.zip);}};for(const x of all.slice(0,Math.min(4,count)))add(x);for(const minDistance of [7,10,13,20,26]){if(selected.length>=count)break;add(all.find(x=>!seen.has(x.zip)&&x.distance>=minDistance));}for(const x of all){if(selected.length>=count)break;add(x);}return selected.slice(0,count);}
function groupQueries(interests,radius,exclusions){const z=sampleZips(radius,8),cats=interests.length?interests.map(x=>`(${x})`):GROUP_LENS,suffix=exclusionQuery(exclusions,'groups'),q=[];for(let i=0;i<z.length;i++){const x=z[i],a=cats[i%cats.length],b=cats[(i+1)%cats.length];q.push(`\"${x.city}\" \"${x.zip}\" Ohio (association OR society OR club OR organization OR guild OR chapter OR museum OR historical OR heritage OR nonprofit) ${suffix}`);q.push(`\"${x.city}\" \"${x.zip}\" Ohio ${a} ${suffix}`);q.push(`\"${x.city}\" \"${x.zip}\" Ohio ${b} ${suffix}`);}return q;}
function eventQueries(radius,exclusions){const z=sampleZips(radius,6),suffix=exclusionQuery(exclusions,'events');return z.map(x=>`\"${x.city}\" \"${x.zip}\" Ohio ${EVENT_LENS} ${suffix}`);}
function jobQueries(interests,radius,exclusions,partTime){const z=sampleZips(radius,8),cats=interests.length?interests:JOB_LENS,suffix=exclusionQuery(exclusions,'jobs'),pt=partTime?' (\"part-time\" OR \"part time\")':'';return z.map((x,i)=>`\"${x.city}\" \"${x.zip}\" Ohio \"${cats[i%cats.length]}\" (jobs OR careers OR hiring OR employment)${pt} ${suffix}`);}
function pageLocation(page,radius){return bestLocation(`${page.title} ${page.description} ${page.html.slice(0,60000)}`,radius);}
function addressFromJsonLocation(location){if(!location)return '';if(typeof location==='string')return clean(location);const a=location.address||location;return clean([a?.streetAddress,a?.addressLocality,a?.addressRegion,a?.postalCode].filter(Boolean).join(', '));}
function parseJsonLd(page){const out=[];for(const m of page.html.matchAll(/<script[^>]+type=[\"']application\/ld\+json[\"'][^>]*>([\s\S]*?)<\/script>/gi)){try{const data=JSON.parse(m[1].trim());const stack=Array.isArray(data)?data:[data];for(const root of stack){const nodes=[root,...(Array.isArray(root?.['@graph'])?root['@graph']:[])];for(const x of nodes)if(x&&typeof x==='object')out.push(x);}}catch{}}return out;}
function extractAddress(text){const m=String(text||'').match(/\b\d{1,6}\s+[A-Za-z0-9.'#&-]+(?:\s+[A-Za-z0-9.'#&-]+){0,6}\s+(?:street|st|road|rd|avenue|ave|drive|dr|lane|ln|boulevard|blvd|highway|hwy|parkway|pkwy|circle|cir|court|ct|trail|trl|way|place|pl|terrace|ter|route|rte)\b[^\n]{0,100}?,?\s+[A-Za-z .'-]+,?\s+OH(?:IO)?\s+\d{5}(?:-\d{4})?\b/i);return m?m[0]:'';}
function makeGroup(page,radius,candidateLocation=null){const loc=pageLocation(page,radius)||candidateLocation;if(!loc)return null;const address=extractAddress(clean(page.html));return {title:page.title||host(page.url),name:page.title||host(page.url),url:page.url,link:page.url,description:page.description||clean(page.html).slice(0,500),address,location:`${loc.city}, OH ${loc.zip}`,city:loc.city,state:'OH',zip:loc.zip,distance:loc.distance,distanceMiles:loc.distance,source:'organic-search',discoverySource:'organic-search'};}
function validGroup(page,c,radius,exclusions){const t=`${page.title} ${page.description} ${page.html.slice(0,60000)} ${evidence(c)}`;if(GROUP_JUNK_HOST_RE.test(host(page.url))||GROUP_JUNK_TITLE_RE.test(`${page.title} ${page.description}`)||MUNICIPAL_GROUP_RE.test(page.title))return false;return ORG_RE.test(t)&&!isExcluded(t,exclusions,'groups')&&!NOISE_RE.test(t)&&!!pageLocation(page,radius);}
function parseEvents(page,org,radius,exclusions){const events=[];for(const x of parseJsonLd(page)){const type=Array.isArray(x?.['@type'])?x['@type'].join(' '):String(x?.['@type']||'');if(!/Event/i.test(type)||!x.name)continue;const address=addressFromJsonLocation(x.location);const combined=`${x.name} ${x.description||''} ${address}`;if(!EVENT_RE.test(combined)||isExcluded(combined,exclusions,'events')||NOISE_RE.test(combined))continue;const best=bestLocation(combined,radius);if(!best||!address)continue;const url=x.url?new URL(x.url,page.url).href:page.url;events.push({title:clean(x.name),name:clean(x.name),url,link:url,organization:org.name,address,location:`${best.city}, OH ${best.zip}`,city:best.city,state:'OH',zip:best.zip,distance:best.distance,distanceMiles:best.distance,date:x.startDate||'',endDate:x.endDate||'',description:clean(x.description||'').slice(0,1000),source:'organic-event-jsonld',discoverySource:'organic-search'});}return events;}
function parseJobsFromJsonLd(page,partTime,exclusions,radius){const jobs=[];for(const x of parseJsonLd(page)){const type=Array.isArray(x?.['@type'])?x['@type'].join(' '):String(x?.['@type']||'');if(!/JobPosting/i.test(type)||!x.title)continue;const address=addressFromJsonLocation(x.jobLocation);const text=`${x.title} ${x.description||''} ${address} ${x.hiringOrganization?.name||''}`;if(partTime&&!/part[- ]?time/i.test(`${x.employmentType||''} ${text}`))continue;if(isExcluded(text,exclusions,'jobs')||NOISE_RE.test(text))continue;const best=bestLocation(`${text} ${page.title}`,radius);if(!best||!address)continue;const url=x.url?new URL(x.url,page.url).href:page.url;jobs.push({title:clean(x.title),name:clean(x.title),url,link:url,organization:clean(x.hiringOrganization?.name||''),address,location:`${best.city}, OH ${best.zip}`,city:best.city,state:'OH',zip:best.zip,distance:best.distance,distanceMiles:best.distance,employmentType:clean(x.employmentType||''),datePosted:x.datePosted||'',description:clean(x.description||'').slice(0,1200),source:'organic-job-jsonld',discoverySource:'organic-search'});}return jobs;}
function makeSearchJob(page,radius,partTime,exclusions){const loc=pageLocation(page,radius);if(!loc)return null;const title=page.title||host(page.url),text=`${title} ${page.description} ${clean(page.html).slice(0,18000)}`,address=extractAddress(text);if(!JOB_RE.test(text)||JOB_JUNK_TITLE_RE.test(title)||isExcluded(text,exclusions,'jobs')||NOISE_RE.test(text)||!address)return null;if(partTime&&!/part[- ]?time/i.test(text))return null;return {title,name:title,url:page.url,link:page.url,organization:'Organic local discovery',address,location:`${loc.city}, OH ${loc.zip}`,city:loc.city,state:'OH',zip:loc.zip,distance:loc.distance,distanceMiles:loc.distance,description:page.description||clean(page.html).slice(0,900),source:'organic-job-page',discoverySource:'organic-search'};}
export async function discoverAll({interests=[],city='Mesopotamia',state='OH',groupRadius=30,eventRadius=30,jobRadius=15,partTime=true,searchParams=new URLSearchParams()}){
 const exclusions=parseExclusions(searchParams),budget={used:0,limit:64},diagnostics=[],groups=[],events=[],jobs=[];
 const groupCandidates=new Map();
 for(const query of groupQueries(interests,groupRadius,exclusions).slice(0,18)){if(budget.used>=budget.limit)break;const r=await search(query,budget);diagnostics.push({stage:'group-search',query,candidates:r.results.length,status:r.status||0,error:r.error||null});for(const c of r.results){const g=gate(c,'groups',groupRadius,exclusions);if(!g.ok){diagnostics.push({stage:'group-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,geoEvidence:evidence(c)});continue;}groupCandidates.set(key(c.url),{...c,score:scoreGroup(c),location:g.location});}}
 const rankedGroups=[...groupCandidates.values()].sort((a,b)=>b.score-a.score).slice(0,8);
 for(const c of rankedGroups){if(budget.used>=budget.limit)break;const p=await fetchPage(c.url,budget);if(!p){diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'fetch failed'});continue;}if(validGroup(p,c,groupRadius,exclusions)){const g=makeGroup(p,groupRadius,c.location);if(g){groups.push(g);diagnostics.push({stage:'group-validation',url:c.url,accepted:true});}}else diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'organization quality, address, or page geography failed'});}
 const eventCandidates=new Map();
 for(const query of eventQueries(eventRadius,exclusions)){if(budget.used>=budget.limit)break;const r=await search(query,budget);diagnostics.push({stage:'event-search',query,candidates:r.results.length,status:r.status||0,error:r.error||null});for(const c of r.results){const g=gate(c,'events',eventRadius,exclusions);if(!g.ok){diagnostics.push({stage:'event-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,geoEvidence:evidence(c)});continue;}eventCandidates.set(key(c.url),{...c,score:scoreEvent(c),location:g.location});}}
 const rankedEvents=[...eventCandidates.values()].sort((a,b)=>b.score-a.score).slice(0,8);
 for(const c of rankedEvents){if(budget.used>=budget.limit)break;const p=await fetchPage(c.url,budget);if(!p)continue;const org={name:p.title||host(p.url)};const parsed=parseEvents(p,org,eventRadius,exclusions);if(parsed.length)events.push(...parsed);else{const text=clean(p.html).slice(0,16000),loc=pageLocation(p,eventRadius);if(loc&&EVENT_RE.test(`${p.title} ${p.description} ${text}`)){const address=extractAddress(text);if(address)events.push({title:p.title||host(p.url),name:p.title||host(p.url),url:p.url,link:p.url,organization:'Organic local discovery',address,location:`${loc.city}, OH ${loc.zip}`,city:loc.city,state:'OH',zip:loc.zip,distance:loc.distance,distanceMiles:loc.distance,description:p.description||text.slice(0,700),source:'organic-event-page',discoverySource:'organic-search'});}}diagnostics.push({stage:'event-page-parse',organization:org.name,candidates:parsed.length});}
 const jobCandidates=new Map();
 for(const query of jobQueries(interests,jobRadius,exclusions,partTime)){if(budget.used>=budget.limit)break;const r=await search(query,budget);diagnostics.push({stage:'job-search',query,candidates:r.results.length,status:r.status||0,error:r.error||null});for(const c of r.results){const g=gate(c,'jobs',jobRadius,exclusions);if(!g.ok){diagnostics.push({stage:'job-prefetch-gate',url:c.url,accepted:false,rejected:g.reason,geoEvidence:evidence(c)});continue;}jobCandidates.set(key(c.url),{...c,score:scoreJob(c),location:g.location});}}
 const rankedJobs=[...jobCandidates.values()].sort((a,b)=>b.score-a.score).slice(0,10);
 for(const c of rankedJobs){if(budget.used>=budget.limit)break;const p=await fetchPage(c.url,budget);if(!p)continue;const parsed=parseJobsFromJsonLd(p,partTime,exclusions,jobRadius);if(parsed.length)jobs.push(...parsed);else{const fallback=makeSearchJob(p,jobRadius,partTime,exclusions);if(fallback)jobs.push(fallback);}diagnostics.push({stage:'job-page-parse',organization:p.title||host(p.url),candidates:parsed.length});}
 const dedupe=(items)=>{const seen=new Set();return items.filter(x=>{const k=`${x.url||''}|${x.title||''}`.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;});};
 return {groups:dedupe(groups),events:dedupe(events),jobs:dedupe(jobs),diagnostics,budget,discoveryHealth:{organicGroups:groups.length,organicEvents:events.length,jobs:jobs.length,fallbackActivated:false,hardZipGate:true,prefetchFiltering:true,searchEvidence:true,independentRadii:true,configurableExclusions:true,broaderQueryCoverage:true,organizationQualityFiltering:true,budgetReservedForJobs:true},coverage:{homeZip:'44439',groupRadius,eventRadius,jobRadius,groupEligibleZipCount:eligibleZips(groupRadius).length,eventEligibleZipCount:eligibleZips(eventRadius).length,jobEligibleZipCount:eligibleZips(jobRadius).length,hardZipGate:true,prefetchFiltering:true,searchEvidence:true,independentRadii:true,configurableExclusions:true,diagnosticLocalAnchors:true}};
}