export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
    if (request.method === "OPTIONS") return new Response(null,{headers:cors});
    try {
      if (url.pathname === "/") return json({ok:true,name:"Opportunity Finder Worker",version:VERSION,build:BUILD,architecture:"organization-first",sources:["trusted local organizations","regional search","direct organization calendars","public job search","USAJOBS"]},cors);
      if (url.pathname === "/test") return json({ok:true,diagnostic:true,version:VERSION,build:BUILD,architecture:"organization-first",limits:{fetch:FETCH_LIMIT,event:EVENT_LIMIT}},cors);
      const p=Object.fromEntries(url.searchParams.entries());
      const home=parseHomeLocation(p.home||"");
      const city=p.city||home.city||"Mesopotamia", state=p.state||home.state||"OH";
      const radius=clamp(Number(p.radius||75),1,100), interests=split(p.interests);
      if(url.pathname==="/groups") { const r=await discoverGroups(interests,city,state,radius,env); return json({...r,items:r.groups,events:undefined,jobs:undefined},cors); }
      if(url.pathname==="/events") { const r=await discoverAll(interests,city,state,radius,env); return json({...r,items:r.events,groups:undefined,jobs:undefined,uniqueCount:r.events.length},cors); }
      if(url.pathname==="/jobs") { const r=await discoverJobs(interests,city,state,radius,p.partTime!=="false",env); return json(r,cors); }
      if(url.pathname==="/discover") return json(await discoverAll(interests,city,state,radius,env),cors);
      return json({ok:false,error:"Not found",version:VERSION,build:BUILD},cors,404);
    } catch(e) { return json({ok:false,diagnostic:true,error:errorMessage(e),version:VERSION,build:BUILD},cors,500); }
  }
};

const VERSION="3.9.1";
const BUILD="v3.9.1-direct-source-discovery";
const FETCH_LIMIT=72;
const EVENT_LIMIT=24;
const DANCE_RE=/\bdance\b|dancing|ballroom|ballet|tap dance|jazz dance|dance studio|dance academy/i;
const AMISH_RE=/\bamish\b/i;
const JUNK_HOST_RE=/(?:facebook|instagram|linkedin|youtube|tiktok|pinterest|twitter|x\.com|wikipedia|yelp|tripadvisor)\./i;
const OUTSIDE_RE=/\b(?:new jersey|new york|pennsylvania|michigan|indiana|kentucky|west virginia)\b/i;
const OH_RE=/\b(?:ohio|oh)\b/i;
const REGION_RE=/\b(?:trumbull|warren|geauga|portage|ashtabula|mahoning|columbiana|summit|lake|cuyahoga|northeast ohio)\b/i;
const ORG_RE=/(?:association|society|club|guild|chapter|council|league|organization|organisation|foundation|conservancy|preservation|collective|fellowship|alliance|coalition|volunteer group)/i;
const VENUE_RE=/(?:museum|library|historic site|historical site|heritage|nature center|nature centre|arboretum|botanical garden|fairgrounds|community center|community centre|cultural center|cultural centre|observatory|visitor center|visitor centre|homestead|mill)/i;
const EVENT_RE=/(?:event|calendar|meeting|workshop|program|programme|exhibit|exhibition|festival|fair|lecture|tour|open house|class|demo|demonstration|registration|tickets|admission|rsvp)/i;
const CAREER_RE=/(?:career|careers|employment|work with us|join our team|job openings|apply now)/i;
const ARTICLE_RE=/(?:news|newspaper|press release|obituary|recipe|restaurant review|podcast|weather|scoreboard|politics|election)/i;
const SEEDS=[
  {name:"Trumbull Beekeepers Association",url:"https://www.trumbullbeekeepers.org/",location:"Cortland, OH 44410",type:"beekeeping",description:"Local beekeeping association serving Trumbull County and surrounding Northeast Ohio."},
  {name:"Western Reserve Artist Blacksmith Association",url:"https://www.wraba.com/",location:"Burton, OH 44021",type:"blacksmithing",description:"Regional nonprofit organization dedicated to preserving and demonstrating the art of blacksmithing."},
  {name:"Century Village Museum",url:"https://centuryvillagemuseum.org/",location:"Burton, OH 44021",type:"museum / history",description:"Historical educational center and living-history museum in Burton, Ohio."},
  {name:"Trumbull County Historical Society",url:"https://www.trumbullcountyhistory.com/",location:"Warren, OH 44483",type:"museum / history",description:"Trumbull County historical society, museum, collections, research, and public programs."},
  {name:"Mesopotamia Memorial and Historical Association",url:"https://sites.google.com/trumbullcountyhistory.org/trumbull-history-hub/home/mesopotamia",location:"Mesopotamia, OH 44430",type:"museum / history",description:"Local historical association and museum in Mesopotamia, Ohio."}
];
const JOB_SOURCES=[{url:"https://www.neo-rls.org/view_job_postings.php",name:"Northeast Ohio Regional Library System"}];
const EVENT_SOURCES=[
  {url:"https://centuryvillagemuseum.org/events-calendar/",org:"Century Village Museum"},
  {url:"https://www.trumbullcountyhistory.com/",org:"Trumbull County Historical Society"},
  {url:"https://www.wraba.com/",org:"Western Reserve Artist Blacksmith Association"},
  {url:"https://www.trumbullbeekeepers.org/",org:"Trumbull Beekeepers Association"}
];
const CITY_COORDS={"mesopotamia,oh":[41.461,-80.955],"cortland,oh":[41.330,-80.726],"warren,oh":[41.237,-80.818],"burton,oh":[41.471,-81.145],"middlefield,oh":[41.465,-81.073],"niles,oh":[41.182,-80.765],"youngstown,oh":[41.099,-80.649],"aurora,oh":[41.317,-81.345],"mentor,oh":[41.666,-81.339],"cleveland,oh":[41.499,-81.694],"akron,oh":[41.081,-81.519],"kirtland,oh":[41.628,-81.361],"howland,oh":[41.252,-80.745]};
function json(data,cors,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"Content-Type":"application/json; charset=utf-8",...cors}})}
function errorMessage(e){return e instanceof Error?e.message:String(e)}
function clamp(n,a,b){return Math.min(Math.max(Number.isFinite(n)?n:a,a),b)}
function clean(s){return String(s||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]*>/g," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"').replace(/&#39;|&#x27;/gi,"'").replace(/\s+/g," ").trim()}
function norm(s){return clean(s).toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function split(s){return String(s||"").split(",").map(x=>x.trim()).filter(Boolean)}
function isHttp(u){try{return /^https?:$/.test(new URL(u).protocol)}catch{return false}}
function abs(u,b){try{return new URL(u||b.href,b.href).href}catch{return b.href}}
function key(a,b){return norm(a)+"|"+urlKey(b)}
function urlKey(u){try{const x=new URL(u);return x.hostname.toLowerCase()+x.pathname.replace(/\/$/,"")}catch{return norm(u)}}
function parseHomeLocation(v){const p=String(v||"").split(",").map(x=>x.trim());return {city:p[0]||"",state:p[1]||""}}
function cityKey(s){const p=String(s||"").split(",").map(x=>norm(x));if(p.length<2)return "";return p[0]+","+(p[1]==="ohio"?"oh":p[1])}
function distanceMiles(a,b){const A=CITY_COORDS[cityKey(a)],B=CITY_COORDS[cityKey(b)];if(!A||!B)return null;const r=Math.PI/180,lat1=A[0]*r,lat2=B[0]*r,dlat=(B[0]-A[0])*r,dlon=(B[1]-A[1])*r,h=Math.sin(dlat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dlon/2)**2;return Math.round(3958.8*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h)))}
function geoScore(text,city,state){const t=norm(text),oh=/^(oh|ohio)$/i.test(state),hasState=oh?OH_RE.test(t):new RegExp("\\b"+esc(state)+"\\b","i").test(t),hasCity=new RegExp("\\b"+esc(city)+"\\b","i").test(t),region=oh?REGION_RE.test(t):false;let s=hasState?45:0;if(hasState&&hasCity)s+=35;if(hasState&&region)s+=20;return {score:Math.min(100,s),hasState,hasCity}}
function esc(s){return String(s||"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function locationFromText(t,city,state){const m=String(t).match(new RegExp(".{0,60}\\b"+esc(city)+"\\b.{0,80}","i"));return clean(m?m[0]:city+", "+state)}
async function fetchText(url,options={},budget){if(budget&&budget.used>=budget.limit)return {ok:false,status:0,text:"",error:"fetch budget exhausted"};if(budget)budget.used++;try{const r=await fetch(url,{...options,redirect:"follow",headers:{"User-Agent":"Opportunity-Finder/3.9.1","Accept":"text/html,application/xhtml+xml,application/xml,application/json,text/xml,*/*",...(options.headers||{})}});const text=await r.text();return {ok:r.ok,status:r.status,text,contentType:r.headers.get("content-type")||""}}catch(e){return {ok:false,status:0,text:"",error:errorMessage(e)}}}
async function searchWeb(q,env,budget){const endpoint=env?.SEARCH_ENDPOINT||"https://www.bing.com/search",u=new URL(endpoint);u.searchParams.set(env?.SEARCH_QUERY_PARAM||"q",q);u.searchParams.set("count","10");const r=await fetchText(u.href,{},budget);if(!r.ok)return {...r,urls:[]};const urls=[];for(const m of r.text.matchAll(/<li[^>]+class=["'][^"']*b_algo[^"']*["'][^>]*>[\s\S]*?<h2[^>]*>\s*<a[^>]+href=["']([^"']+)["']/gi)){try{const x=new URL(m[1]);if(isHttp(x.href)&&!JUNK_HOST_RE.test(x.hostname)&&!urls.includes(x.href))urls.push(x.href)}catch{}if(urls.length>=10)break}return {...r,urls}}
function targetQueries(interests,city,state){const base=interests.length?interests:["local history","museums","historical societies","beekeeping","blacksmithing","reenactment","traditional crafts","native plants","woodworking","astronomy","cycling","clubs","guilds"];const places=[`"${city}" ${state}`,`"Trumbull County" Ohio`,`"Northeast Ohio"`,`"Geauga County" Ohio`,`"Portage County" Ohio`,`"Mahoning County" Ohio`];return [...new Set(base.slice(0,8).flatMap((x,i)=>[`${places[i%places.length]} "${x}" (association OR society OR club OR guild OR organization) -dance`,`${places[i%places.length]} "${x}" (museum OR historical OR nature OR workshop OR class) -dance`]))].slice(0,12)}
function acceptUrl(u,state){if(!isHttp(u))return false;try{const x=new URL(u);if(JUNK_HOST_RE.test(x.hostname))return false;const t=norm(x.href);if(/^(oh|ohio)$/i.test(state)&&OUTSIDE_RE.test(t)&&!OH_RE.test(t)&&!REGION_RE.test(t))return false;return true}catch{return false}}
function trustedGroups(city,state,radius){return SEEDS.map(s=>{const d=distanceMiles(`${city}, ${state}`,s.location);return {...s,id:key(s.name,s.url),score:100,confidence:100,locationScore:100,distance:d,distanceMiles:d,source:"trusted regional source",discoveryQuality:"verified"}}).filter(x=>x.distance==null||x.distance<=radius)}
async function discoverGroups(interests,city,state,radius,env){const budget={used:0,limit:FETCH_LIMIT-EVENT_LIMIT},diag=[],found=[...trustedGroups(city,state,radius)],candidates=[];for(const q of targetQueries(interests,city,state)){const r=await searchWeb(q,env,budget);diag.push({stage:"group-search",query:q,ok:r.ok,status:r.status,candidates:r.urls?.length||0,error:r.error||null});for(const u of r.urls||[])if(acceptUrl(u,state))candidates.push(u)}for(const u of [...new Set(candidates)].slice(0,16)){const r=await fetchText(u,{},budget);if(!r.ok){diag.push({stage:"group-validation",url:u,ok:false,status:r.status,rejected:r.error||"fetch failed"});continue}const g=parseGroupPage(r.text,u,interests,city,state,radius);diag.push({stage:"group-validation",url:u,ok:true,status:r.status,accepted:g?1:0,rejected:g?null:"validation failed"});if(g)found.push(g)}const groups=dedupe(found).sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,100);return {ok:true,version:VERSION,build:BUILD,architecture:"organization-first",city,state,radius,interests,groups,counts:{groups:groups.length,events:0,jobs:0},stages:{validatedOrganizations:groups.length},fetchBudget:budget,diagnostics:diag,notes:["Trusted local organizations are anchors; search results are validated before acceptance.","Dance organizations are excluded."]}}
function parseGroupPage(html,url,interests,city,state,radius){const base=new URL(url),title=clean((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||""),desc=clean((html.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']*)/i)||[])[1]||""),head=clean(html.slice(0,18000));if(DANCE_RE.test(title+" "+desc)||AMISH_RE.test(title+" "+desc)||ARTICLE_RE.test(title)&&!ORG_RE.test(title+" "+desc))return null;const identity=title+" "+desc+" "+head.slice(0,2200);if(!(ORG_RE.test(identity)||VENUE_RE.test(identity)))return null;const geo=geoScore(head,city,state);if(geo.score<45)return null;const d=distanceMiles(`${city}, ${state}`,locationFromText(head,city,state));if(d!=null&&d>radius)return null;let name=title.replace(/\s*[|–—-]\s*.+$/," ").trim();if(!name||/^(home|welcome|official site|homepage|index)$/i.test(name))name=clean(base.hostname.replace(/^www\./," ").split(".")[0]).replace(/[-_]/g," ");const score=relevance(name+" "+desc,interests)+geo.score;return {id:key(name,base.href),name,url:base.href,description:desc.slice(0,900),type:classify(name+" "+desc),location:locationFromText(head,city,state),score,confidence:Math.min(100,55+geo.score/2),locationScore:geo.score,distance:d,distanceMiles:d,source:"validated public page",discoveryQuality:"verified"}}
function classify(t){const x=norm(t);if(/beekeep|apiary/.test(x))return"beekeeping";if(/blacksmith|forge|smithing/.test(x))return"blacksmithing";if(/reenact|living history|sca/.test(x))return"reenactment";if(/museum|historical|heritage|preservation/.test(x))return"museum / history";if(/garden|native plant|nature/.test(x))return"nature / gardening";if(/astronom/.test(x))return"astronomy";return"community group"}
function dedupe(a){const m=new Map();for(const x of a){const k=key(x.name,x.url);if(!m.has(k))m.set(k,x)}return [...m.values()]}
async function discoverAll(interests,city,state,radius,env){const g=await discoverGroups(interests,city,state,radius,env),budget={used:g.fetchBudget.used,limit:FETCH_LIMIT},events=[],diag=[...g.diagnostics];for(const src of EVENT_SOURCES){if(budget.used>=budget.limit)break;const org=g.groups.find(x=>x.name===src.org)||SEEDS.find(x=>x.name===src.org);if(!org)continue;const r=await fetchText(src.url,{},budget);if(!r.ok){diag.push({stage:"trusted-event-source",url:src.url,ok:false,status:r.status,rejected:r.error||"fetch failed"});continue}const found=parseEvents(r.text,src.url,interests,city,state,org,radius);diag.push({stage:"trusted-event-source",url:src.url,ok:true,status:r.status,accepted:found.length});events.push(...found)}const eq=[...new Set(g.groups.slice(0,8).flatMap(o=>[`${o.name} events ${city} Ohio`,`"${o.name}" calendar ${city} Ohio`]))];for(const q of eq){if(budget.used>=FETCH_LIMIT)break;const r=await searchWeb(q,env,budget);for(const u of r.urls||[]){if(budget.used>=FETCH_LIMIT)break;const f=await fetchText(u,{},budget);if(!f.ok)continue;events.push(...parseEvents(f.text,u,interests,city,state,radius))}}const unique=dedupeEvents(events).slice(0,100);return {...g,events:unique,groups:g.groups,counts:{groups:g.groups.length,events:unique.length,jobs:0},stages:{...g.stages,eventCandidates:unique.length,validatedEvents:unique.length},fetchBudget:budget,diagnostics:diag}}
function parseEvents(html,url,interests,city,state,org,radius){const base=new URL(url),out=[],jsonld=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const x=JSON.parse(m[1].trim());jsonld.push(...(Array.isArray(x)?x:(x&&x["@graph"]?[...x["@graph"]]:[x])))}catch{}}for(const x of jsonld){const typ=Array.isArray(x?.["@type"])?x["@type"].join(" "):String(x?.["@type"]||"");if(!/Event/i.test(typ)||!x.name)continue;const loc=fmtLoc(x.location),text=clean(`${x.name} ${x.description||""} ${loc}`),geo=geoScore(text+" "+clean(html.slice(0,10000)),city,state),d=distanceMiles(`${city}, ${state}`,loc);if(DANCE_RE.test(text)||AMISH_RE.test(text)||geo.score<45||(d!=null&&d>radius))continue;out.push({id:key(x.name,x.url||base.href),title:clean(x.name),description:clean(x.description||"").slice(0,1000),url:abs(x.url||base.href,base),date:x.startDate||"",endDate:x.endDate||"",location:loc||`${city}, ${state}`,organizer:clean(typeof x.organizer==="object"?x.organizer?.name||org?.name: x.organizer||org?.name||""),source:"JSON-LD Event",score:relevance(text,interests)+geo.score,type:"event",discoveryQuality:"verified",locationScore:geo.score,distance:d,distanceMiles:d,org:org?.name||"",host:org?.name||""})}for(const m of html.matchAll(/<(article|li|section)[^>]*>([\s\S]*?)<\/\1>/gi)){const b=clean(m[2]);if(b.length<60||!EVENT_RE.test(b)||DANCE_RE.test(b)||AMISH_RE.test(b))continue;const date=findDate(b);if(!date)continue;const geo=geoScore(b,city,state),d=distanceMiles(`${city}, ${state}`,locationFromText(b,city,state));if(geo.score<45||(d!=null&&d>radius))continue;const h=clean((m[2].match(/<h[1-4][^>]*>([\s\S]*?)<\/h[1-4]>/i)||[])[1]||b.slice(0,120));if(h.length<5)continue;out.push({id:key(h,base.href+date),title:h,description:b.slice(0,1000),url:base.href,date,location:locationFromText(b,city,state),organizer:org?.name||"",source:"validated event block",score:relevance(b,interests)+geo.score,type:"event",discoveryQuality:"verified",locationScore:geo.score,distance:d,distanceMiles:d,org:org?.name||"",host:org?.name||""})}return dedupeEvents(out)}
function dedupeEvents(a){const m=new Map();for(const x of a){const k=key(x.title,(x.url||"")+x.date);if(!m.has(k))m.set(k,x)}return [...m.values()]}
function fmtLoc(x){if(!x)return"";if(typeof x==="string")return clean(x);if(Array.isArray(x))return x.map(fmtLoc).filter(Boolean).join("; ");if(x.address)return [x.name,fmtLoc(x.address)].filter(Boolean).join(", ");return [x.name,x.streetAddress,x.addressLocality,x.addressRegion,x.postalCode].filter(Boolean).join(", ")}
function findDate(t){const m=String(t).match(/\b(?:20\d{2}[-/]\d{1,2}[-/]\d{1,2}|\d{1,2}[/-]\d{1,2}[/-]20\d{2}|(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t(?:ember)?)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+\d{1,2}(?:,\s*20\d{2})?)\b/i);return m?m[0]:""}
function relevance(t,is){const x=norm(t);return (is||[]).reduce((s,i)=>s+(x.includes(norm(i))?10:0),0)}
async function discoverJobs(interests,city,state,radius,partTime,env){const budget={used:0,limit:FETCH_LIMIT},items=[],diag=[];const base=interests.length?interests:["museum","historic preservation","archaeology","bike mechanic","welding","fabrication","woodworking","artisan","crafts"];const qs=[...new Set(base.slice(0,8).map(x=>`"${x}" "${city}" ${state} jobs -dance`))];for(const q of qs){const r=await searchWeb(q,env,budget);diag.push({stage:"job-search",query:q,ok:r.ok,status:r.status,candidates:r.urls?.length||0});for(const u of r.urls||[]){if(!acceptUrl(u,state))continue;const f=await fetchText(u,{},budget);if(!f.ok)continue;items.push(...parseJobPage(f.text,u,interests,city,state,radius,partTime))}}for(const src of JOB_SOURCES){if(budget.used>=FETCH_LIMIT)break;const r=await fetchText(src.url,{},budget);diag.push({stage:"regional-job-source",source:src.name,url:src.url,ok:r.ok,status:r.status});if(r.ok)items.push(...parseJobPage(r.text,src.url,interests,city,state,radius,partTime))}for(const q of base.slice(0,4)){if(budget.used>=FETCH_LIMIT)break;const u=new URL("https://data.usajobs.gov/api/search");u.searchParams.set("Keyword",q);u.searchParams.set("LocationName",`${city}, ${state}`);u.searchParams.set("Radius",String(radius));u.searchParams.set("ResultsPerPage","20");const h={};if(env?.USAJOBS_KEY)h.AuthorizationKey=env.USAJOBS_KEY;if(env?.USAJOBS_EMAIL)h["User-Agent"]=env.USAJOBS_EMAIL;const r=await fetchText(u.href,{headers:h},budget);if(!r.ok)continue;try{const j=JSON.parse(r.text);for(const z of j?.SearchResult?.SearchResultItems||[]){const d=z.MatchedObjectDescriptor||{},loc=d.PositionLocationDisplay||"",geo=geoScore(loc,city,state),dist=distanceMiles(`${city}, ${state}`,loc);if(geo.score<45||(dist!=null&&dist>radius))continue;items.push({id:key(d.PositionID||d.PositionTitle,d.PositionURI||u.href),title:d.PositionTitle||"USAJOBS opportunity",organization:d.OrganizationName||"",url:d.PositionURI||"https://www.usajobs.gov/",description:clean(d.UserArea?.Details?.JobSummary||"").slice(0,1100),date:d.PublicationStartDate||"",closeDate:d.ApplicationCloseDate||"",location:loc,employmentType:(d.PositionScheduleType?.[0]?.Name)||"",source:"USAJOBS",score:relevance(`${d.PositionTitle||""} ${d.OrganizationName||""}`,interests)+geo.score,type:"job",discoveryQuality:"verified",locationScore:geo.score,distance:dist,distanceMiles:dist})}}catch{}}const unique=dedupeJobs(items);return {ok:true,version:VERSION,build:BUILD,city,state,radius,partTime,counts:{jobs:unique.length},items:unique,jobs:unique,fetchBudget:budget,diagnostics:diag}}
function parseJobPage(html,url,interests,city,state,radius,partTime){const base=new URL(url),out=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const x=JSON.parse(m[1].trim());for(const z of Array.isArray(x)?x:[x]){const typ=Array.isArray(z?.["@type"])?z["@type"].join(" "):String(z?.["@type"]||"");if(!/JobPosting/i.test(typ)||!z.title)continue;const loc=fmtLoc(z.jobLocation),geo=geoScore(`${loc} ${z.description||""}`,city,state),dist=distanceMiles(`${city}, ${state}`,loc),text=clean(`${z.title} ${z.description||""}`);if(DANCE_RE.test(text)||AMISH_RE.test(text)||geo.score<45||(dist!=null&&dist>radius))continue;if(partTime&&z.employmentType&&!/part|temporary|seasonal/i.test(String(z.employmentType)))continue;out.push({id:key(z.title,z.url||base.href),title:clean(z.title),organization:clean(typeof z.hiringOrganization==="object"?z.hiringOrganization?.name||"":z.hiringOrganization||""),url:abs(z.url||base.href,base),description:clean(z.description||"").slice(0,1100),date:z.datePosted||"",closeDate:z.validThrough||"",location:loc,employmentType:clean(z.employmentType||""),source:"JSON-LD JobPosting",score:relevance(text,interests)+geo.score,type:"job",discoveryQuality:"verified",locationScore:geo.score,distance:dist,distanceMiles:dist})}}catch{}}for(const m of html.matchAll(/<(article|li|section|div)[^>]*>([\s\S]*?)<\/\1>/gi)){const b=clean(m[2]);if(b.length<80||b.length>4000||!/(?:part[ -]?time|full[ -]?time|hourly|salary|apply|position|job)/i.test(b)||AMISH_RE.test(b))continue;const geo=geoScore(b,city,state),dist=distanceMiles(`${city}, ${state}`,locationFromText(b,city,state));if(geo.score<45||(dist!=null&&dist>radius)||DANCE_RE.test(b))continue;if(partTime&&!/part[ -]?time/i.test(b))continue;if(!/(?:museum|library|maintenance|maker|fabricat|weld|woodwork|mechanic|historic|archaeol|craft|preservation|park|outdoor)/i.test(b))continue;const title=clean((m[2].match(/<h[1-4][^>]*>([\s\S]*?)<\/h[1-4]>/i)||[])[1]||b.slice(0,100));if(title.length<5)continue;out.push({id:key(title,base.href+title),title,organization:"",url:base.href,description:b.slice(0,1100),date:"",closeDate:"",location:locationFromText(b,city,state),employmentType:/part[ -]?time/i.test(b)?"Part-time":"",source:"validated public job listing",score:relevance(b,interests)+geo.score,type:"job",discoveryQuality:"validated-lead",locationScore:geo.score,distance:dist,distanceMiles:dist})}return dedupeJobs(out)}
function dedupeJobs(a){const m=new Map();for(const x of a){const k=key(x.title,x.url);if(!m.has(k))m.set(k,x)}return [...m.values()].slice(0,100)}
export { parseGroupPage, parseEvents, parseJobPage, geoScore, distanceMiles, parseHomeLocation };
