import { HOME_ZIP, eligibleZips, passesHardZipGate, bestLocation } from './zip-geo.js';

const DEFAULT_INTERESTS = ['community organizations','historical societies','museums','nature conservation','traditional crafts','archaeology','volunteer groups','gardening clubs'];
const GROUP_TYPES = ['association','society','club','guild','chapter','organization','foundation','conservancy','preservation','museum','library','historical','heritage','nature','conservation','volunteer','community'];
const DANCE_RE = /\bdance\b|dancing|ballroom|ballet|tap dance|jazz dance|dance studio|dance academy/i;
const NOISE_RE = /ancient mesopotamia|mesopotamian|mesopotamia river|louisiana|church point/i;
const JUNK_HOST_RE = /(?:facebook|instagram|linkedin|youtube|tiktok|pinterest|x\.com|twitter|wikipedia|yelp|tripadvisor|google|googleusercontent|googleapis|accounts|drive)\./i;
const CONTENT_HOST_RE = /(?:indeed|glassdoor|ziprecruiter|simplyhired|monster|britannica|merriam-webster|newsbreak|restaurantji|weather)\./i;
const ORG_RE = /association|society|club|guild|chapter|organization|organisation|foundation|conservancy|preservation|museum|library|historical|heritage|nature|conservation|volunteer|community/i;
const EVENT_RE = /event|calendar|meeting|workshop|program|programme|exhibit|exhibition|festival|fair|lecture|tour|open house|class|demo|demonstration|registration|tickets|rsvp/i;
const LOCAL_RE = /ohio|trumbull|warren|northeast ohio|geauga|portage|ashtabula|mahoning|columbiana|summit|lake|cuyahoga/i;

const TRUSTED_LOCAL = [
  { name:'Trumbull County Beekeepers', url:'https://www.trumbullbeekeepers.org/', zip:'44410', city:'Cortland' },
  { name:'Century Village Museum', url:'https://centuryvillagemuseum.org/', zip:'44021', city:'Burton' },
  { name:'Trumbull County Historical Society', url:'https://www.trumbullcountyhistory.com/', zip:'44483', city:'Warren' }
];

function clean(s) { return String(s || '').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&#x27;/gi,"'").replace(/\s+/g,' ').trim(); }
function host(url) { try { return new URL(url).hostname.toLowerCase(); } catch { return ''; } }
function key(url) { try { const u=new URL(url); return `${u.hostname.toLowerCase()}${u.pathname.replace(/\/$/,'')}`; } catch { return String(url || '').toLowerCase(); } }
function validUrl(url) { try { const u=new URL(url); return /^https?:$/.test(u.protocol) && !JUNK_HOST_RE.test(u.hostname) && !CONTENT_HOST_RE.test(u.hostname); } catch { return false; } }
function unwrapSearchUrl(url) { try { const u=new URL(url); if (!/(^|\.)bing\.com$/i.test(u.hostname) || !u.pathname.startsWith('/ck/a')) return url; let raw=u.searchParams.get('u')||''; if(raw.startsWith('a1')) raw=raw.slice(2); raw=raw.replace(/-/g,'+').replace(/_/g,'/'); while(raw.length%4) raw+='='; const decoded=atob(raw); return /^https?:\/\//i.test(decoded)?decoded:url; } catch { return url; } }
function extractSearchResults(html) {
  const out=[],seen=new Set();
  const blocks=[...html.matchAll(/<li[^>]+class=["'][^"']*b_algo[^"']*["'][^>]*>([\s\S]*?)<\/li>/gi)].map(m=>m[1]);
  for(const block of blocks){ const m=block.match(/<h2[^>]*>\s*<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i); if(!m)continue; const url=unwrapSearchUrl(m[1]),text=clean(m[2]),evidence=clean(block); if(!validUrl(url)||!text||seen.has(key(url)))continue; seen.add(key(url)); out.push({url,text,evidence}); }
  return out.slice(0,12);
}
async function search(query,budget){ if(budget.used>=budget.limit)return {urls:[],error:'fetch budget exhausted'}; budget.used++; try{const u=new URL('https://www.bing.com/search');u.searchParams.set('q',query);u.searchParams.set('count','10');const r=await fetch(u.href,{redirect:'follow',headers:{'User-Agent':'Opportunity-Finder/3.13-organic-zip-gate',Accept:'text/html,application/xhtml+xml'}});const html=await r.text();if(!r.ok)return {urls:[],status:r.status};return {urls:extractSearchResults(html),status:r.status};}catch(e){return {urls:[],error:String(e?.message||e)};} }
async function fetchPage(url,budget){ if(budget.used>=budget.limit)return null; budget.used++; try{const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Opportunity-Finder/3.13-organic-zip-gate',Accept:'text/html,application/xhtml+xml'}});if(!r.ok)return null;const html=await r.text();return {url:r.url||url,html,title:clean((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||url),description:clean((html.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']*)/i)||[])[1]||'')};}catch{return null;} }
function terms(interests){return (interests.length?interests:DEFAULT_INTERESTS).flatMap(x=>String(x).split(/[,;]+/).map(y=>y.trim()).filter(Boolean)).slice(0,8);}
function querySet(interests,state,radius){const zips=eligibleZips(radius).slice(0,12),cats=terms(interests),qs=[];for(let i=0;i<cats.length&&qs.length<12;i++){const z=zips[i%zips.length];qs.push(`"${z.zip}" "${z.city}" ${state} "${cats[i]}" (${GROUP_TYPES.slice(0,8).join(' OR ')}) -dance -"ancient Mesopotamia" -Mesopotamian`);}return [...new Set(qs)];}
function score(c,interests){const t=`${c.text} ${c.url} ${c.evidence||''}`.toLowerCase();let s=0;if(ORG_RE.test(t))s+=25;if(LOCAL_RE.test(t))s+=15;if(/\b\d{5}\b/.test(t))s+=10;for(const x of terms(interests))if(t.includes(x.toLowerCase()))s+=8;if(DANCE_RE.test(t)||NOISE_RE.test(t))s-=100;return s;}
function gate(candidate,radius){const evidence=`${candidate.url} ${candidate.text} ${candidate.evidence||''}`;if(DANCE_RE.test(evidence))return {ok:false,reason:'dance exclusion'};if(NOISE_RE.test(evidence))return {ok:false,reason:'search noise'};if(!passesHardZipGate(evidence,radius))return {ok:false,reason:'hard ZIP gate failed before fetch'};return {ok:true,location:bestLocation(evidence,radius)};}
function locationFromPage(page,radius){return bestLocation(`${page.title} ${page.description} ${page.html.slice(0,40000)}`,radius);}
function makeGroup(page,candidate,interests,radius){const loc=locationFromPage(page,radius);if(!loc)return null;return {title:page.title||host(page.url),name:page.title||host(page.url),url:page.url,link:page.url,description:page.description||clean(page.html).slice(0,500),location:`${loc.city}, OH ${loc.zip}`,city:loc.city,state:'OH',zip:loc.zip,distance:loc.distance,distanceMiles:loc.distance,source:'organic-search',discoverySource:'organic-search',relevance:score(candidate,interests)};}
function organizationValid(page,candidate,interests,radius){const text=clean(`${page.title} ${page.description} ${page.html.slice(0,50000)} ${candidate.evidence||''}`);if(DANCE_RE.test(text)||NOISE_RE.test(text))return false;if(!ORG_RE.test(text)&&!/(museum|library|nature center|historic site|community center)/i.test(text))return false;return !!locationFromPage(page,radius);}
async function discoverGroups(interests,state,budget,radius){const diagnostics=[],candidates=new Map();for(const query of querySet(interests,state,radius)){const r=await search(query,budget);diagnostics.push({stage:'organic-group-search',query,candidates:r.urls.length,status:r.status||0,error:r.error||null});for(const c of r.urls){const g=gate(c,radius);if(!g.ok){diagnostics.push({stage:'group-prefetch-zip-gate',url:c.url,accepted:false,rejected:g.reason});continue;}if(score(c,interests)<=0)continue;candidates.set(key(c.url),c);}if(budget.used>=budget.limit)break;}
  const ranked=[...candidates.values()].sort((a,b)=>score(b,interests)-score(a,interests)).slice(0,12),groups=[];
  for(const c of ranked){const p=await fetchPage(c.url,budget);if(!p){diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'fetch failed'});continue;}if(!organizationValid(p,c,interests,radius)){diagnostics.push({stage:'group-validation',url:c.url,accepted:false,rejected:'organization or ZIP validation failed'});continue;}const item=makeGroup(p,c,interests,radius);if(item&&!groups.some(x=>host(x.url)===host(item.url)))groups.push(item);if(groups.length>=8||budget.used>=budget.limit)break;}
  return {groups,diagnostics,candidateCount:candidates.size};}
function trustedGroups(radius){return TRUSTED_LOCAL.map(x=>({...x,title:x.name,name:x.name,url:x.url,link:x.url,location:`${x.city}, OH ${x.zip}`,state:'OH',source:'verified local seed',discoverySource:'trusted-local-seed',distance:bestLocation(`${x.city} OH ${x.zip}`,radius)?.distance ?? null,distanceMiles:bestLocation(`${x.city} OH ${x.zip}`,radius)?.distance ?? null,relevance:100})).filter(x=>x.distance!==null);}
function eventFromJsonLd(x,base,org,radius){const loc=typeof x.location==='string'?clean(x.location):clean([x.location?.name,x.location?.streetAddress,x.location?.addressLocality,x.location?.addressRegion,x.location?.postalCode].filter(Boolean).join(', '));const combined=`${x.name||''} ${x.description||''} ${loc}`;if(!x.name||DANCE_RE.test(combined)||NOISE_RE.test(combined)||!EVENT_RE.test(combined))return null;const best=bestLocation(combined,radius);if(!best)return null;return {title:clean(x.name),name:clean(x.name),url:x.url?new URL(x.url,base).href:base,link:x.url?new URL(x.url,base).href:base,organization:org.name,location:`${best.city}, OH ${best.zip}`,city:best.city,state:'OH',zip:best.zip,distance:best.distance,distanceMiles:best.distance,date:x.startDate||'',endDate:x.endDate||'',description:clean(x.description||'').slice(0,1000),source:'organic-event-jsonld',discoverySource:'organic-search'};}
function parseOrganicEvents(page,org,radius){const events=[];for(const m of page.html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const data=JSON.parse(m[1].trim());const list=Array.isArray(data)?data:data?.['@graph']||[data];for(const x of list){const types=Array.isArray(x?.['@type'])?x['@type'].join(' '):String(x?.['@type']||'');if(/Event/i.test(types)){const e=eventFromJsonLd(x,page.url,org,radius);if(e)events.push(e);}}}catch{}}
  return events;}
async function discoverEvents(groups,interests,state,budget,radius){const events=[],diagnostics=[];for(const org of groups.slice(0,8)){if(budget.used>=budget.limit)break;const p=await fetchPage(org.url,budget);if(!p)continue;const found=parseOrganicEvents(p,org,radius);diagnostics.push({stage:'organic-event-links',organization:org.name,candidates:found.length});events.push(...found);if(events.length>=8)break;}
  if(events.length<8){for(const org of groups.slice(0,6)){if(budget.used>=budget.limit)break;const query=`"${org.name}" (events OR calendar OR workshop OR program) -dance`;const r=await search(query,budget);diagnostics.push({stage:'organic-event-search',organization:org.name,query,candidates:r.urls.length,status:r.status||0});for(const c of r.urls){const g=gate(c,radius);if(!g.ok){diagnostics.push({stage:'event-prefetch-zip-gate',url:c.url,accepted:false,rejected:g.reason});continue;}if(!EVENT_RE.test(`${c.text} ${c.evidence||''}`))continue;const p=await fetchPage(c.url,budget);if(!p)continue;const found=parseOrganicEvents(p,org,radius);events.push(...found);if(events.length>=8)break;} }}
  const seen=new Set(),unique=events.filter(e=>{const k=`${e.title.toLowerCase()}|${e.url}`;if(seen.has(k))return false;seen.add(k);return true;});return {events:unique.slice(0,8),diagnostics};}

export async function organicDiscover(interests=[],city='Mesopotamia',state='OH',groupRadius=30,eventRadius=30){const budget={used:0,limit:44},started=Date.now();const groupResult=await discoverGroups(interests,state,budget,groupRadius);const seeded=trustedGroups(groupRadius);const groups=[...seeded,...groupResult.groups].filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i);const eventResult=await discoverEvents(groups,interests,state,budget,eventRadius);return {ok:true,version:'3.13.0',build:'v3.13.0-independent-organic-radii',groups,events:eventResult.events,jobs:[],fetchBudget:budget,coverage:{homeZip:HOME_ZIP,groupRadius,eventRadius,groupEligibleZips:eligibleZips(groupRadius).map(x=>x.zip),eventEligibleZips:eligibleZips(eventRadius).map(x=>x.zip),zipFirst:true,organicGroups:groups.length,organicEvents:eventResult.events.length,candidateCount:groupResult.candidateCount},diagnostics:[...groupResult.diagnostics,...eventResult.diagnostics],durationMs:Date.now()-started};}
